- core/cap-0002.md
first draft
discussion located here: https://github.com/stellar/stellar-core/issues/1464
> added Transaction level signature verification (cap0002)

- contents/cap-0003/get_offer_stats.sql
- core/cap-0003.md
Implements discussion from #36
> Asset backed offers (draft-0002)

- core/cap-0002.md
Signed-off-by: Rafał Malinowski <rafal.przemyslaw.malinowski@gmail.com>
> improve examples for CAP-0002

- core/readme.md
forgot to do this when adding 0002
> updated CAP TOC to include cap-0002

- core/cap-0001.md
Resolves #53 
Mostly copy/pasted from the issue
Added a few details from the final implementation
> Added BumpSequence cap-0001

- core/cap-0002.md
- core/readme.md
https://github.com/stellar/stellar-core/issues/1464
> Mark cap-0002 as final

- ecosystem/sep-0001.md
80% of people are currently reaching out for support through Telegram. I think it deserves a place here
> Add Telegram to contact information

- drafts/draft-0002.md
Moved from https://www.stellar.org/developers/guides/attachment.html with small improvements.
Close #28.
> Attachments

- ecosystem/sep-0005.md
Added the .NET Standard 2.0 Implementation I crated to the Other Implementations section of README
> Added Other Implementation for .NET Standard 2.0

- ecosystem/sep-0001.md
- ecosystem/sep-0003.md
- ecosystem/sep-0006.md
- ecosystem/sep-0009.md
- ecosystem/sep-0010.md
Proposed [SEP-6](https://github.com/stellar/stellar-protocol/blob/sep0006-expansion/ecosystem/sep-0006.md).
New [SEP-9](https://github.com/stellar/stellar-protocol/blob/sep0006-expansion/ecosystem/sep-0009.md): defines standard AML / KYC fields
New [SEP-10](https://github.com/stellar/stellar-protocol/blob/sep0006-expansion/ecosystem/sep-0010.md): defines Stellar web authentication protocol
Major changes:
* `/customer` endpoint added to allow upload of KYC information
* Added web authentication flow
* Deposit and withdrawal endpoints modified to add new kinds of responses:
* non-interactive customer information needed response: Issuer needs more information about user before deposit or withdrawal information can be given
* interactive customer information needed response: Issuer needs user …
> Extend SEP-6

- ecosystem/readme.md
I added sep 9/10 bullet points to the TOC. Please merge when it's appropriate to list them.
> add new seps to table of contents

- ecosystem/sep-0009.md
> Improve bank_account, add ip_address

- ecosystem/sep-0001.md
> Add collateral_address_messages and status=private

- ecosystem/readme.md
- ecosystem/sep-0001.md
- ecosystem/sep-0008.md
- move sep8 to ecosystem folder
- update sep list
- update sep0001 with sep0008 info
> sep8 plumbing

- ecosystem/sep-0003.md
> fix hyperlink address

- drafts/draft-0004.md
Draft for #96 (SEP for Issuing large numbers of Assets).
I'm also going to create a simple reference implementation for the described service in JS. It will work as a ready-to-use app for serving assets metadata from the static files in the TOML format (@nullstyle arguments look convincing) and as a bootstrap service for the custom implementation.
> SEP draft for Dynamic Asset Metadata

- core/cap-0004.md
- core/readme.md
Added cap-0004, which describes improvements to rounding for cross offer.
> Added cap-0004

- core/cap-0006.md
- core/readme.md
> Draft of cap-0006

- ecosystem/sep-0008.md
Found some minor typos while reading through this.
> SEP 8 typos

- ecosystem/sep-0006.md
See the full new [SEP](https://github.com/tomquisel/stellar-protocol/blob/add-fee-endpoint/ecosystem/sep-0006.md) and the new [fee section](https://github.com/tomquisel/stellar-protocol/blob/add-fee-endpoint/ecosystem/sep-0006.md#fee).
> Add fee endpoint for complex fee structures

- core/cap-0016.md
- core/readme.md
Migrating from https://github.com/stellar/stellar-protocol/issues/146
closes https://github.com/stellar/stellar-protocol/issues/146
> add cap0016: cosigned assets

- core/cap-0018.md
- core/readme.md
> First draft of cap-0018 which introduces fine-grained authorization

- core/cap-0015.md
* Fee bumping logic moved to the TransactionEnvelope level.
* Updated fee charging logic to comply with CAP-0005 according to comments from Nicolas.
> Updated CAP-0015 proposal with modifications on the TransactionEnvelope level

- ecosystem/sep-0013.md
Just as an example of the simplifications that #203 and #209 would help #205 with.
> Demonstrate SEP-13 post CAP-7 and CAP-8

- ecosystem/sep-0013a.md
This draft explains how CAP-13 can be used to provide a convenient and easy-to-implement deposit experience for new Stellar network users.
You can see the full SEP [here](https://github.com/tomquisel/stellar-protocol/blob/tq/sep-13a-draft/ecosystem/sep-0013a.md).
> Draft of SEP-13a

- ecosystem/sep-0001.md
> Change DEPOSIT_SERVER -> TRANSFER_SERVER.

- core/README.md
- core/cap-0016.md
- core/cap-0018.md
- core/cap-0019.md
* CAP-0016 moves to rejected in favor of CAP-0018.
* CAP-0018 moves to Accepted
* CAP-0019 moves to FCP: Acceptance
> Update CAPs for week of 3/21/19.

- core/README.md
Clarified the intent about the "Accepted" stage, and added an additional
Implemented and Implementation Review stage.
> Add implementation review stage after acceptance.

- core/README.md
- core/cap-0005.md
- core/cap-0006.md
- core/cap-0020.md
After adding the Implementation Review stage, moved all the v11 CAPs to it.
> Move all protocol v11 CAPs to Implementation Review.

- ecosystem/sep-0001.md
* State that phone numbers should be in E.164 (international) format.
* Fix the existing address' format in the example.
Helps address the concerns here: https://github.com/stellar/docs/issues/404
> SEP-0001: Add formatting clarifications.

- ecosystem/sep-0006.md
Adds a refunded transaction status.
> Add refunded transaction status to SEP-0006

- core/README.md
- ecosystem/README.md
Ideally will make things a bit more readable for those first looking at proposals.
> Move Drafts into their own table in each README.

- ecosystem/README.md
- ecosystem/sep-0020.md
SEP-0020 has been gaining traction without comment for some time, so
we're going to move this past FCP to Active.
> Move SEP-0020 to Active.

- ecosystem/sep-0001.md
Closes https://github.com/stellar/stellar-protocol/issues/352
> Reference Sui's stellar.toml checker

- ecosystem/sep-0012.md
> Add deprecation warning

- ecosystem/README.md
> SDF SEP Team member changes

- ecosystem/sep-0006.md
> Make login / signup form on missing JWT optional

- core/README.md
> fix up wording of CAP Implementation Review status

- core/README.md
- core/cap-0026.md
https://github.com/stellar/stellar-core/pull/2297
> Mark CAP0026 implemented

- core/cap-0015.md
Updates to CAP-0015 so that it matches the in-progress implementation from https://github.com/stellar/stellar-core/pull/2258
> Updated CAP-0015

- ecosystem/sep-0001.md
@tomerweller is there any reason these should be separate fields?
> [SEP1] Add sep10 to the list of SIGNING_KEY usages

- ecosystem/README.md
- ecosystem/sep-0006.md
- ecosystem/sep-0024.md
I merged SEP24 but this will actually update the README and deprecate SEP6
> Replace sep6 with sep24

- ecosystem/sep-0024.md
> Remove email_address from /deposit params

- ecosystem/sep-0010.md
- ecosystem/sep-0024.md
Add more information about the preflight (OPTIONS) request to both sep 10 and 24 CORS section.
> Add preflight request information to SEP 10 and 24

- ecosystem/sep-0010.md
The JWT link is not opening the proper URL without "https://".
> Fix broken JWT link in SEP-10

- ecosystem/sep-0027.md
Addresses https://github.com/stellar/stellar-protocol/issues/464 and https://github.com/stellar/stellar-protocol/pull/460
> SEP27: Asset Information

- core/cap_0028.md
Issue - https://github.com/stellar/stellar-protocol/issues/495
> added cap for removing one time signers

- ecosystem/README.md
Add SEP-28 to list of SEPs in README.
I forgot to do so when I merged #487.
> SEP-28: Add to SEPs list in README

- core/cap-0023.md
These are the changes after considering the feedback from @MonsieurNicolas in https://github.com/stellar/stellar-protocol/issues/303#issuecomment-572732557.
> Introduce boolean expression trees to CAP-0023

- ecosystem/sep-0011.md
Demo is here if you want to see it live: https://stellarguard.github.io/txrep/demo/
> Add JS implementation for SEP-0011, Txrep

- core/cap-0023.md
Seems like a word was missing here
> Add "...exists" to clarify

- ecosystem/sep-0025.md
This PR adds the limitations section as well as corrects and adds the comments in the code snippet. It makes the logic on the provider side align with the one on the client side.
> Update SEP-25 with detail on lumen requirement

- core/README.md
- core/cap-0028.md
- core/cap-0030.md
I think these two CAPs are ready for final comment period.  If I'm right, this PR changes their statuses + updates the readme table.
> Change status of CAP 28 + CAP 30 to FCP

- core/README.md
- core/cap-0015.md
- core/cap-0023.md
- core/cap-0027.md
- core/cap-0028.md
- core/cap-0030.md
Update statuses for 5 CAPs:
- CAP 15 `Draft` --> `Accepted`
- CAP 23 `FCP` --> `Draft`
- CAP 27 `Draft` --> `FCP`
- CAP 28 `FCP` --> `Accepted`
- CAP 30 `FCP` --> `Accepted`
> Update CAP statuses (CAPs 15, 23, 27, 28, and 30)

- core/README.md
- core/cap-0015.md
- core/cap-0027.md
- CAP-15 from `Accepted` to `Implemented`, + added protocol 13 designation
- CAP-27 from `FCP` to `Accepted`
- Removed `Implementation Review` period from README because it's not something we actually use.
> update CAP statuses

- core/README.md
- core/cap-0018.md
- core/cap-0028.md
- core/cap-0030.md
For CAPs 18, 28, and 30:
- Indicate Protocol 13 inclusion
- Change status from `Accepted` to `Implemented`
> Rice2000 update cap status

- ecosystem/sep-0001.md
fix minor inconsistencies in terminology
> more consistent terminology

- ecosystem/sep-0006.md
- ecosystem/sep-0012.md
* Updating SEP-12 to play well with non-interactive SEP-6
* Typos
* Resolves #587 
* Follow-Up to #582
> Updating SEP-12 to play well with non-interactive SEP-6

- core/cap-0015.md
Synchronize CAP-0015 with the actual implementation from https://github.com/stellar/stellar-core/pull/2419
> Update CAP-0015 to match the implementation

- core/README.md
- core/cap-0027.md
Update CAP 27 status (from `Accepted` to `Implemented`)
> CAP-0027: Update status to implemented

- core/README.md
- core/cap-0031.md
Initial CAP-0031 (Sponsored Reserves) draft.
> Draft of CAP-0031

- core/cap-0031.md
Add discussion link to CAP-31.
@jonjove has started a discussion thread on the stellar-dev mailing list now and we should direct people there from the CAP.
> CAP-0031: Add discussion link

- ecosystem/sep-0031.md
Address one of leigh's comments that i missed in the original PR
> Use 401 instead of 403 for sep10

- ecosystem/README.md
- ecosystem/sep-0032.md
Add a proposal for user-friendly asset addresses that includes a process for verifying them.
There does not seem to be a consistent user-friendly approach to referencing or resolving unique assets in products that are built on Stellar. Each wallet or application I use has a different approach and
it is an unpleasant experience to find assets using their issuer addresses.
Please take discussion to the [stellar-dev mailing list](https://groups.google.com/d/topic/stellar-dev/rWThI_BIs0Y). Any minor quick feedback such as typos, etc feel free to leave here in the PR.
> SEP-0032: Add proposal for user-friendly asset addresses and process for verifying them

- ecosystem/sep-0030.md
Add discussion link.
There is a discussion thread on the stellar-dev mailing list but the link is missing from the proposal.
> SEP-0030: Add discussion link

- core/README.md
- core/cap-0023.md
- core/cap-0033.md
Change status of CAP 23 and CAP 33 to `FCP` to kick off the Final Comment Period.
> Rice2000 prot14 ca ps fcp

- ecosystem/sep-0031.md
> SEP-12: Organize thoughts on _sep12_type parameters

- ecosystem/sep-0012.md
resolves stellar/stellar-protocol#153
> SEP-12: Add memo and memo_type to SEP-12 DELETE request body

- core/README.md
- core/cap-0015.md
- core/cap-0018.md
- core/cap-0027.md
- core/cap-0028.md
- core/cap-0030.md
Changed status of CAPs 15, 18, 27, 28 and 30 to `Final` now that the network has upgraded to Protocol 13.
> Rice2000 protocol13 caps to final

- core/cap-0034.md
The first draft of this document, for stellar-protocol issue #622 , was merged in PR #671 .  I'm starting this draft pull request for commentary on an in-progress second draft.
> Second draft of CAP-0034 (change closetime semantics)

- core/README.md
- core/cap-0034.md
- Update readme to mark CAP-34 as `FCP`
- Update CAP-34 header to indicate `FCP`
> Rice2000 cap 34 fcp

- core/cap-0020.md
> Fix mismatch between CAP-20 and implementation of CAP-20

- ecosystem/README.md
- ecosystem/sep-0035.md
This protocol outlines an ID scheme for historical operations, so they can be consistently indexed across the ecosystem. It closes https://github.com/stellar/nebula/issues/18.
> SEP-35: Operation IDs

- core/README.md
- core/cap-0023.md
- core/cap-0033.md
- core/cap-0034.md
Change status of CAP-23, CAP-33, and CAP-34 to `Implemented`
> Rice2000 mark protocol 14 implemented

- ecosystem/sep-0012.md
resolves stellar/stellar-protocol#734
> SEP-12: DELETE Content-type and Request Body Args

- ecosystem/sep-0010.md
Replace my obsolete email address with Github/Keybase username.
> SEP-0010: Update contact info (no spec changes)

- core/cap-0035.md
CAP proposal to enable a clawback operation for regulated assets to meet regulatory requirements for securities in many jurisdictions.
> Clawback CAP

- cap-template.md
- core/README.md
resolves #624
This PR makes changes to the CAP process based on feedback from previous protocol changes.
> updated CAP process with working groups (meta)

- ecosystem/sep-0031.md
resolves stellar/stellar-protocol#749
No functional change. I just replaced the `Payment Flow` section with `Sending Flow` and `Receiver Flow`.
> Split payment flow into sender and receiver flows

- core/README.md
- core/cap-0035.md
**Why**
This CAP is missing from the README. We are going to evaluate this CAP and the work needed in order to move it forward.
> Add CAP-35 to readme

- ecosystem/sep-0001.md
Adding a bit of language in the 3 license fields at legal's suggestion.
> SEP-0001: Improve language on organization licensing fields

- core/cap-0035.md
Tidy minor formatting issues and some typos.
I'm doing a pass over CAP-35 and will be making some changes to it to address @MonsieurNicolas's concerns discussed [here](https://groups.google.com/g/stellar-dev/c/hPhkXhrl5-Y/m/k8bx_0rnCQAJ), and noticed these things during the pass.
> CAP-0035: Tidy minor formatting, typos, etc

- core/cap-0035.md
Update CAP-35 to use the new CAP template.
@MonsieurNicolas requested this [here](https://groups.google.com/g/stellar-dev/c/hPhkXhrl5-Y/m/k8bx_0rnCQAJ).
Note: This change makes no tangible functional changes to the proposal. I plan to make functional changes separately.
> CAP-0035: Update to use new CAP template

- ecosystem/sep-0031.md
> SEP-31: added Content-Type policy section

- core/cap-0035.md
Fix the XDR diff.
It was corrupted by https://github.com/stellar/stellar-protocol/pull/834#discussion_r558791172.
> CAP-0035: fix diff

- ecosystem/sep-0009.md
resolves #732 
Simple fix for bad type labels for image attributes.
> SEP-9: corrected image data types from string to binary

- ecosystem/sep-0024.md
> removed iframe mention

- ecosystem/sep-0001.md
- add `asset_attestation` field to `Currency Documentation`
> SEP-0001: Add assetation_of_reserves

- core/README.md
- core/cap-0035.md
Change README and CAP-35 to move CAP-35 from `FCP: Acceptance` to `Accepted`
> CAP-0035: Change from FCP to Accepted

- core/cap-0029.md
This PR addresses the comments from  https://github.com/stellar/stellar-protocol/issues/843#issuecomment-783546059.
> CAP-0029 - Add missing sections

- core/README.md
- core/cap-0029.md
Mark CAP-29 as `FCP: Acceptance` in README and CAP-29.
> Rice2000 cap 29 fcp

- ecosystem/sep-0009.md
resolves stellar/stellar-protocol#832
Adds a clarification to the organization fields section on how field names should be specified.
> SEP-9: Clarify organization dot notation

- ecosystem/sep-0001.md
Update toml-check URL
Removed deprecated AUTH_SERVER from example
> SEP-0001: Update toml-check URL and remove deprecated AUTH_SERVER from example

- core/README.md
- core/cap-0029.md
> Rice2000 cap 29 accepted

- ecosystem/sep-0023.md
this will help referring to individual changes from other proposals
> sep23: modifying horizon changes to be numbered

- core/cap-0037.md
The deposit stake formula was incorrect in the previous revision and it didn't specified rounding direction.
> Fix deposit stake formula

- ecosystem/README.md
- ecosystem/sep-0038.md
resolves #901 
This protocol enables anchors to accept off-chain assets in exchange for different on-chain assets, and vice versa. Specifically, it enables anchors to provide quotes that can referenced within the context of existing Stellar Ecosystem Proposals. How the exchange of assets is facilitated is outside the scope of this document.
Once the protocol has been merged, SEP-6 & SEP-31 will be updated to accept quote IDs provided by this API.
> SEP-0038: Request for Quote API

- ecosystem/sep-0033.md
- add project url of [Golang implementation](https://github.com/StellarCN/stellar-identicon-go).
> SEP-0033: add project url of Go implementation.

- core/cap-0038.md
Change CAP-38 to hash identifiers for liquidity pools, and other small fixes.
> CAP-38 Improvements

- core/cap-0038.md
Something to note in this PR -
I changed `ChangeTrustAsset` to `ExpandedTrustLineAsset`, which I then used as a parameter to `SetTrustLineFlagsOp`. I think this PR should be reviewed prior to merging since I changed parts of the proposal that were already changed recently.
> CAP-0038 - Add Authorization and Clawback logic

- core/cap-0038.md
Some minor fixes and added a comment under pool transferability.
> CAP-0038 - Minor fixes

- ecosystem/sep-0031.md
**Context**
As part of an ongoing effort to improve the usability of our protocols, in Q1 of 2021 SDF held an internal review of several SEP titles with the goal of choosing usable, descriptive names. 
Our protocols have developed over many years and as they and the ecosystem have grown, the names that they were originally given have sometimes become less meaningful. We’ve found ourselves often referring to a protocol by its number instead of its title, which can be confusing for new members as it abstracts the meaning of the SEP in discussion. While we’ll continue to use the SEP-# namespace in technical discussions and in order to maintain searchability, this step towards plain language names will hopefully encourage their usage in addition to the numeric shorthand.
**Before: Direct …
> Updating SEP-31 title for clarity and usability

- ecosystem/sep-0024.md
**Context**
As part of an ongoing effort to improve the usability of our protocols, in Q1 of 2021 SDF held an internal review of several SEP titles with the goal of choosing usable, descriptive names. 
Our protocols have developed over many years and as they and the ecosystem have grown, the names that they were originally given have sometimes become less meaningful. We’ve found ourselves often referring to a protocol by its number instead of its title, which can be confusing for new members as it abstracts the meaning of the SEP in discussion. While we’ll continue to use the SEP-# namespace in technical discussions and in order to maintain searchability, this step towards plain language names will hopefully encourage their usage in addition to the numeric shorthand.
**Before: Interactive …
> Updating SEP-24 title for clarity and usability

- core/cap-0038.md
This PR addresses comments from https://github.com/stellar/stellar-protocol/pull/965.
> CAP-0038 - claimable balance on revoke fixes

- ecosystem/sep-0006.md
> SEP-6: fix typos and update wording

- core/cap-0038.md
Fixes a few minor issues in CAP-38, specifically some that were noticed by @ire-and-curses.
> CAP-38: Fixups

- core/README.md
- core/cap-0038.md
Move CAP-38 to `FCP - Acceptance`
> Rice2000 cap 38 fcp

- core/cap-0038.md
This file uses `TRUST_LINE`, not `TRUSTLINE`.
> CAP-0038 - minor formatting change for consistency

- core/README.md
- core/cap-0038.md
Change status of CAP-38 from `FCP - Acceptance` to `Accepted`
> Rice2000 mark cap 38 final

- ecosystem/README.md
Add @marcelosalloum and @rice2000 to the SEP team.
> Lets add @marcelosalloum as well
-- @JakeUrban https://github.com/stellar/stellar-protocol/pull/990#pullrequestreview-697642710
> Good catch @JakeUrban – looking at this again, should we also add @rice2000?
-- @accordeiro https://github.com/stellar/stellar-protocol/pull/990#issuecomment-872545679
> SEP: Add Marcelo and Justin to SEP Team

- core/README.md
- core/cap-0039.md
Change CAP-39's status to rejected.
I am no longer pursuing this proposal.
> CAP-39: Change status to rejected

- ecosystem/sep-0006.md
> SEP-6: Fix typo

- ecosystem/sep-0006.md
> SEP-06: fix json response

- ecosystem/sep-0012.md
- add missing comma
- remove trailing commas
> fix json responses in sep-0012

- core/cap-0038.md
Fixes a small bug in the CAP-38 XDR.
> CAP-38: Add LIQUIDITY_POOL_DEPOSIT_LINE_FULL

- core/cap-0038.md
See https://developers.stellar.org/docs/glossary/liquidity-pool/
> CAP-38: Add protocol version

- ecosystem/sep-0006.md
- ecosystem/sep-0024.md
https://github.com/stellar/stellar-protocol/issues/1083
> SEP-6 / SEP-24: Add pending_user_transfer_complete transaction status

- core/README.md
- core/cap-0021.md
- core/cap-0040.md
Move CAP-21 and CAP-40 to `FCP: Acceptance`
> Rice2000 protocol19 fcp

- core/cap-0045.md
This is an early draft of CAP-0045 that will be expanded in the future. But I wanted to get an early version up since it interacts with our ongoing discussion of CAP-0044.
> First draft of CAP-0045: Speedex - Pricing

- core/cap-0040.md
Clarify order in which signers are checked.
> CAP-0040 - Specify verification order

- core/README.md
- core/cap-0042.md
> Rice2000 cap 42 accept

- core/cap-TBD.md
Draft CAP covering work proposed in core PR https://github.com/stellar/stellar-core/pull/3413
[Rendered](https://github.com/stellar/stellar-protocol/blob/af533c94dc3f84cd77335ce7f0c2b8192ff4d016/core/cap-TBD.md)
> Add draft CAP for smart contract runtime environment

- core/README.md
- core/cap-0047.md
> CAP-0047 - Smart Contract Lifecycle

- ecosystem/sep-0024.md
> SEP-24 - Fix Refund fee amount 

- core/README.md
- core/cap-TBD.md
Initial draft for consideration.
> CAP-53: Draft of contract-data CAP

- ecosystem/sep-0001.md
resolves #1196
Adds an `nft` value to the list of `anchor_asset_type` values.
> SEP-1: add 'nft' to `anchor_asset_type` values

- ecosystem/README.md
- ecosystem/sep-0014.md
As per the mailing list [discussion](https://groups.google.com/g/stellar-dev/c/-S7FIXJAi2A/m/tJJRq_M_AwAJ?utm_medium=email&utm_source=footer)
> SEP-14: change to active

- core/cap-0047.md
Addresses #1259.
I will update rs-stellar-contract-env and rs-stellar-contract-sdk after this change is accepted.
> CAP-0047 - stop using parent and child

- core/cap-0051.md
Resolves https://github.com/stellar/rs-stellar-contract-env/issues/196
> CAP-51: vec_new pass in optional capacity parameter

- ecosystem/sep-0006.md
- ecosystem/sep-0012.md
Adding callback signature requirements from SEP12
> SEP 006: Add callback signature requirement

- ecosystem/sep-0031.md
Adding callback signature requirements from SEP12
> SEP31: Add callback signature requirement

- core/cap-0056.md
> CAP-0056 - Use LedgerCloseMetaV2

- ecosystem/sep-0031.md
> SEP-31: Updated `refunded` status and detailed receiving anchor flow

- ecosystem/sep-0009.md
resolves https://github.com/stellar/stellar-protocol/issues/1301
> SEP-9: add `proof_of_income` field

- core/cap-0046-02.md
- core/cap-0046-06.md
This PR adds some of the proposals mentioned [here](https://docs.google.com/document/d/1IwuwxRVxoRWW8k3ojKQs-RAiW9DlAhMYL2EWlO3L1Cg/edit#) to CAP-0046-06.
> Update built-in token contract semantics

- ecosystem/sep-0009.md
resolves https://github.com/stellar/stellar-protocol/issues/1322
> SEP-9: add proof_of_liveness field

- core/cap-0046-07.md
Integrates various decisions from the mailing list
> Fee CAP updates

- core/cap-0046-07.md
Reflects state of the conversation as of https://discord.com/channels/897514728459468821/1078874094700875826/1083095264212029552
> Fee updates (March 08)

- ecosystem/README.md
- ecosystem/sep-0040.md
- ecosystem/sep-oracle-consumer-interface.md
SEP draft by @mootz12, @markuspluna, @orbitlens following the discussion on the [mailing list](https://groups.google.com/g/stellar-dev/c/KV2XaQzcPPQ).
> Oracle Consumer Interface SEP draft

- core/cap-0046-07.md
- core/cap-0046.md
This mostly brings the specifications up to date with the current state and also adds a bit of details on runtime enforcement.
> Update CAP-0046-07 (Soroban fees)

- core/cap-0046-03.md
- core/cap-0046-10.md
- Rebased on top of the pending runtime PR. 
- Still need to update the "error handing" section but the overall list of host functions are complete.
> Update the host function cap (0046-03)

- core/README.md
- core/cap-0046-02.md
- core/cap-0046-04.md
Closes cap-46-04 and merge its non-obsolete contents into cap-46-02
> [cap-46-02: smart contract lifecycle] describe contract invocation

- core/README.md
- core/cap-0046-01.md
- core/cap-0046-02.md
- core/cap-0046-03.md
- core/cap-0046-05.md
- core/cap-0046-06.md
- core/cap-0046-07.md
- core/cap-0046-08.md
- core/cap-0046-09.md
- core/cap-0046-10.md
- core/cap-0046-11.md
- core/cap-0046-12.md
- core/cap-0046.md
This PR changes the statuses of the Soroban-related CAPs to Awaiting Decision.
> Rice2000 soroban caps awaiting decision

- core/cap-0046-03.md
Keeping it up-to-date with https://github.com/stellar/rs-soroban-env/pull/1240
> Update extend host function names

- core/README.md
- core/cap-0046-01.md
- core/cap-0046-02.md
- core/cap-0046-03.md
- core/cap-0046-05.md
- core/cap-0046-06.md
- core/cap-0046-07.md
- core/cap-0046-08.md
- core/cap-0046-09.md
- core/cap-0046-10.md
- core/cap-0046-11.md
- core/cap-0046-12.md
- core/cap-0046.md
Change status of Soroban CAPs to `Implemented`
> Rice2000 soroban caps implemented

- ecosystem/sep-0006.md
To reduce merge conflicts later on
> Run prettier on SEP-6 doc

- core/cap-0051.md
Add the start of a CAP draft for secp256r1 in the Soroban host interface
> Add the start of a CAP draft for secp256r1 in the Soroban host interface

- core/cap-0046-07.md
Also, rewrite storage write fee rate formula to be easier to understand
> CAP0046-07: handle underspecified cases when fees are too low

- core/README.md
- core/cap-0055.md
- core/cap-0056.md
This adds CAPs for the two near-term improvements discussed over in https://github.com/stellar/stellar-protocol/discussions/1460
> Add drafts for CAP-0055 and CAP-0056, for Soroban instantiation improvements

- core/README.md
- core/cap-0051.md
- core/cap-0053.md
- core/cap-0054.md
- core/cap-0055.md
- core/cap-0056.md
Updated state of the following CAPs to "FCP: Accepted" following the unanimous approval from the CAP Core Team over email to the stellar developer mailing list.
[CAP-51](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0051.md): add support for secp256r1 verification.
[CAP-53](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0053.md): create separate functions for extending the time-to-live for contract instance and contract code.
[CAP-54](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0054.md): lower total costs by refining the Soroban cost model used for VM instantiation into multiple separate and more-accurate costs.
[CAP-55](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0055.md): lower total costs by linking fewer …
> Updated state of approved CAPs to FCP: Accepted

- core/README.md
- core/cap-0051.md
- core/cap-0053.md
- core/cap-0054.md
- core/cap-0055.md
- core/cap-0056.md
The following CAPs have been accepted on the merits of the idea pre-implementation, and are ready for implementation. It is still possible that a CAP may be rejected post-implementation due to the issues that may arise during an initial implementation.
[CAP-51](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0051.md): add support for secp256r1 verification.
[CAP-53](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0053.md): create separate functions for extending the time-to-live for contract instance and contract code.
[CAP-54](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0054.md): lower total costs by refining the Soroban cost model used for VM instantiation into multiple separate and more-accurate costs. …
> CAPs moved to Accepted state

- .github/workflows/prettier.yml
- ecosystem/sep-0001.md
Checkout job was failing in forks
> Fix SEP prettier workflow in forks

- ecosystem/sep-0031.md
Fix the broken mermaid diagram
Tested in Mermaid Live Editor
> [Anchor Platform] Fix sep31 protocal diagram

- core/cap-0060.md
This is a short CAP about the Wasmi register machine. It's mostly not perceptible to users but will alter costs some.
> Add CAP for wasmi register machine.

- ecosystem/sep-0044.md
Update changelog and version of SEP-44.
I missed updating them when I opened and merged:
- https://github.com/stellar/stellar-protocol/pull/1541
> SEP-44: Update changelog and version

- limits/slp-0001.md
I've added a section on the anticipated long-term impact of the change and moved the text/sections around a bit.
> Minor updates for SLP-1.

- limits/slp-0001.md
> SLP-0001 - Fix event numbers

- core/README.md
Small PR - adjusts the `core/README.md` file to reference the correct ecosystem's `README.md` file.
> Update ecosystem guide reference

- ecosystem/sep-0038.md
The country code was switched in https://github.com/stellar/stellar-protocol/pull/1386, but example requests haven't been updated
> [SEP-38] Update example request to use 2 letter country code

- core/cap-0065.md
Just following up on some feedback from @dmkozh about lack of specificity in CAP 0065
> Address some CAP-0065 feedback

- core/cap-0066.md
- Introduce classic entry write fee and provide the respective computation algorithm
- Update the section on the initial network settings both for the new and old values
> Update the fee/resources semantics for CAP-66

- ecosystem/sep-0038.md
This adds support for SEP-45 and fixes some typos.
> SEP-38: Add support for SEP-45 authentication

- core/cap-0046-06.md
- core/cap-0067.md
Also update CAP-0046-06 with some missing details.
> Add set_authorized to CAP-0067

- ecosystem/README.md
- ecosystem/sep-0047.md
- ecosystem/sep-0050.md
This SEP introduces a standardized NFT interface for smart contracts.
By establishing a consistent and flexible interface, this SEP aims to streamline integration and development while maintaining flexibility for developers.
Here is the related [GitHub Discussion](https://github.com/stellar/stellar-protocol/discussions/1674).
Looking forward to community feedback!
> SEP-50: Non-Fungible Tokens

- core/cap-0067.md
> CAP-0067- Fix muxed info 

- core/cap-0067.md
Update as a result of [this](https://github.com/stellar/stellar-protocol/discussions/1553#discussioncomment-12785617)  discussion.
> CAP-0067 - update refund

- core/cap-0067.md
Add the 'stage' to fee events to identify when exactly the fee event has occurred.
> Add the 'stage' to fee events

- ecosystem/sep-0048.md
Thanks @karthikiyer56 for noticing.
> SEP-48: Fix typo

- core/cap-0063.md
As a result of https://github.com/stellar/stellar-core/pull/4715#discussion_r2105459486
> CAP-0063 - preload edge case

- core/README.md
- core/cap-0062.md
- core/cap-0063.md
- core/cap-0065.md
- core/cap-0066.md
- core/cap-0067.md
- core/cap-0068.md
- core/cap-0069.md
- core/cap-0070.md
update protocol 23 CAPs to implemented status
> update protocol 23 CAPs to implemented status

- core/cap-0067.md
These changes were not implemented, and will instead be done in the transaction queue.
> CAP-0067 - remove unimplemented changes

- core/README.md
Per dev mailing list.
See [this thread](https://groups.google.com/g/stellar-dev/c/ZmlSKP1HoDc/m/OnYfxDffAAAJ) for context.
> Updates to CAP core team members
