- ecosystem/sep-0002.md
Ex. Javascript will parse big (int64) integers incorrectly.
> Require memo field to be a string in Federation protocol

- ecosystem/sep-0006.md
Add a transaction history endpoint to SEP-0006. This allows wallets to display status of pending deposit/withdrawals, as well as a history of transactions involving the anchor for a given Stellar account.
> SEP-0006: add transaction history endpoint

- ecosystem/sep-0006.md
In general I can raise many questions for discussion:
- why mixing dates and paging_id, 
- why there is no `order` parameter when querying transactions. 
- shouldn't we be able to fetch transaction by specific `stellar_transaction_id` or `external_transaction_id`
- what is `operation_id` parameter in withdrawal response and why is it not documented?
But in my current PR I tried to be productive and included only things that are a MUST.
I believe that [@fritz](https://stellar-public.slack.com/messages/@fritz/) also had an opinion on that endpoint, you should check with him if he has something to add to the conversation.
> improve transactions endpoint

- README.md
- cap-template.md
- core/readme.md
This is a first step towards having all significant changes going into the core network go through an open process.
It's mostly the same thing than the EIP process except that I had to gut some of the governance as we are not there yet (we need more contributors to reach critical mass).
I didn't modified or tried to specify the process used for SEPs as it doesn't have the same requirements.
> Actually specify the process followed for submiting CAPs

- ecosystem/sep-0003.md
The nonce should be the same when requesting information on a specific transaction.
Currently, the `nonce` functionality that is implemented by bridge does not support fetching information of a transaction that had already been submitted because the `nonce` sent is different every time.
> Specify when `nonce` should be the same

- ecosystem/sep-0001.md
Add is_asset_anchored field to Currency Documentation to allow issuers to state explicitly whether their asset is or is not anchored.  This change would facilitate market interface filtering by asset type.
> Add is_asset_anchored to sep-0001.md

- ecosystem/sep-0001.md
- ecosystem/sep-0010.md
Some updates for SEP-0010: Stellar Web Authentication (based on a work started in #136):
/cc @tomquisel
> A few fixes and improvements for SEP-0010

- ecosystem/sep-0006.md
Provide clearer description of the callback / `postMessage` that occurs at the end of an interactive SEP-6 flow. See the changes in [the interactive response section](https://github.com/stellar/stellar-protocol/blob/sep0006-minor-fixes/ecosystem/sep-0006.md#3-customer-information-needed-interactive) of the SEP.
> Refine interactive SEP-6 flow

- ecosystem/sep-0010.md
> SEP-0010: document validation steps, update examples

- ecosystem/sep-0006.md
Changes:
* Added a `type` field to [SEP-6 Deposit Request](https://github.com/tomquisel/stellar-protocol/blob/85d28a60c15f76814c26ee541f777afb3b7ed4b0/ecosystem/sep-0006.md#request) to support anchors like Tempo that have multiple deposit types
* Added a `choices` field to the field objects in [`/info`](https://github.com/tomquisel/stellar-protocol/blob/85d28a60c15f76814c26ee541f777afb3b7ed4b0/ecosystem/sep-0006.md#response-2) to support fields with a handful of possible values like `type`
> SEP-6: Add a type field to /deposit

- ecosystem/sep-0006.md
Add `interactive_deposit` flag to the [`interactive_customer_info_needed` response](https://github.com/tomquisel/stellar-protocol/blob/bf4931dd09c556f9e62b96d99f44f504b96c48bf/ecosystem/sep-0006.md#3-customer-information-needed-interactive) to `/deposit`.
This is needed for anchors such as AnchorUSD that both collect KYC info and initiate the deposit from within their interactive iframe flow for deposits. It allows the anchor to communicate to the wallet that the wallet does not need to make any more requests to `/deposit` to complete the deposit, as is normally the case.
> SEP-6: support interactive customer info flows that include deposit

- core/cap-0005.md
I simplified how the "effective base fee" is managed (use of derived value instead of parameter going through consensus), this closes potential abuse vectors while simplifying the implementation quite a bit.
I also added a new requirement to allow "replace by fee" to take place.
> Cap0005 updates

- ecosystem/sep-0006.md
Some assets are issued with a different asset code than what they anchor (e.g. WSD and USDT for USD), the language used left it ambiguous which code should be used.
> [SEP-6] Clarify asset codes

- ecosystem/sep-0006.md
The current specification only provides `min_amount` or `max_amount` after requesting `/withdraw` or `/deposit`. Since that happens at the end of the user flow, we don't have access to those values for validation at the time the amount is entered. It would simplify implementation if these were provided as part of `/info`.
> Add min/max to /info response

- core/cap-0014.md
As of protocol version 10, orders are sorted in protocol such that  transactions
for an account are sorted by sequence number (ascending) the order between
accounts is randomized. We propose leaving the transactions un-sorted, but
checking that the order satisfies certain properties.
> Add Cap-0014 Adversarial Transaction Set Ordering

- ecosystem/sep-0011.md
Also, Relax the default for _present to be true if fields/values present.
This still allows transactions a pointer to be made unambiguously NULL
with _present: false, but also means that values can be excerpted
without showing tons of _present: true and still be pastable into
a txrep.
> Fix a bug where zero-length vectors could not be represented.

- ecosystem/sep-0001.md
- is_asset_anchored should be boolean instead of string
- bool changed to boolean for consistency
> consistent definition of boolean fields in stellar.toml

- ecosystem/sep-0006.md
Extending the spec by a note about CORS headers, since they are vital for web clients to use the anchor's endpoints.
As briefly discussed with @tomquisel.
> Add CORS note to SEP-0006

- core/cap_graydon_3b96ae30.md
This is an updated and expanded version of the INITENTRY (and METAENTRY) CAP resulting from the past month of prototyping work over on https://github.com/stellar/stellar-core/pull/1950
I believe it's addressed all the feedback I've got so far from discussion in the community and with other core devs, so I'm proposing this draft for consideration.
> CAP proposal: INITENTRY and METAENTRY.

- ecosystem/sep-0016.md
@p2p is a confusing name, because @ generally prefixes a person's
handle and p2p often stands for peer-to-peer.
> rename @p2p to atp3

- core/cap-0005.md
This PR makes a few changes to CAP005 after a first take on an implementation.
1. Removes mention of replace by fee: the version mentioned here was weak (overlay) and was later deemed insufficient.
2. Replaces the way transactions are randomized during surge pricing, making it "more random"
3. Clarifies when surge pricing actually happens, previous version didn't account for the impossibility of filling up transaction sets
> Cap005 updates (post prototyping)

- core/cap-0006.md
`offerID` was made `int64` [https://github.com/stellar/stellar-core/pull/2044)](here), to make it less error prone in languages that don’t support uint64.
Update the value here to reduce confusion for implementers.
> make offerID int64, as implemented

- ecosystem/sep-0006.md
This PR fixes #309. 
The goal is to detail the steps that should be taken during the deposit flow, when the given Stellar account doesn't have a trust line for the asset that is being deposited.
> Update SEP-6 to clarify the trust line creation flow on /deposit

- ecosystem/sep-0006.md
Provide a mechanism in  SEP-6 that anchors can use to indicate that their deposit, withdrawal, and transaction endpoints require [SEP-10](sep-0010.md) authentication.
> SEP-6: allow anchors to indicate auth required

- ecosystem/sep-0001.md
This proposal streamlines the stellar.toml specification in the wake of SEP20, essentially implementing a suggestion @MonsieurNicolas made in the discussion of that SEP.
Rather than expressing attributes of validators independently in the Account Information global fields, organizations would create a list of validators (really an array of tables) similar to the Currency Documentation section.
Each validator an organization runs would get its own entry, and relevant info would be presented per validator.  This change will make it easier to add new properties to validators (if we want to), and to write tools like automated configuration generation.
This proposal also gets rid of fields that no longer match stellar core configurations (such as DESIRED_BASE_FEE and …
> Change how sep1 presents validator information

- ecosystem/sep-0006.md
If an anchor is requiring interactive customer information, it may be possible to omit `dest` in the initial withdraw API call.  The reason being that the anchor can collect the dest information interactively while they collect the customer information.
I would propose that anchors that want to declare that dest is required should do so via the Info endpoint.
> Mark `dest` as optional in SEP-0006 withdraw

- core/README.md
- core/cap-0015.md
- core/cap-0021.md
Fixes #334.
* Moving CAP-0015 to accepted.
* CAP-0021 back to Draft until CAP-0022 is accepted.
> Update CAPs for week of 06/27/2019.

- ecosystem/sep-0010.md
* Clarify choice of passphrase for signatures in SEP-10
* Also add an optional response parameter to the challenge endpoint: `network_passphrase` to make debugging signature issues easier.
* Replace outdated reference to SEP-6 with reference to SEP-12
Addresses problem mentioned in https://github.com/stellar/go/pull/1468
Closes #339 
@nebolsin I'd love your feedback.
> Clarify choice of passphrase in SEP-10

- ecosystem/sep-0006.md
Describe recommended wallet and anchor implementations to demystify all the possible ways of implementing SEP-6. See new [recommendations section](https://github.com/stellar/stellar-protocol/blob/tomquisel-patch-1/ecosystem/sep-0006.md#recommendations).
> Describe recommended SEP-6 implementations

- ecosystem/sep-0006.md
Make the interactive flow easier to implement for anchors by allowing 404 responses for incomplete transactions. This means the anchor will not need to create a transaction entry in its database as soon as `/deposit` is hit. Instead, it can wait for successful completion of the interactive flow, and the wallet will handle that correctly.
Also add a note for anchors to test their interactive forms on mobile.
> Allow 404 /transaction responses

- ecosystem/sep-0006.md
Interactive withdraws can facilitate multiple types so no need for the wallet to know in advance.
> SEP6: make withdraw type optional

- ecosystem/sep-0010.md
Match the wording from Sep6 to require cross-origin headers to allow browsers to interact with the protocol
> Require cross-origin on sep10

- ecosystem/sep-0001.md
Updating SEP to be in line with https://github.com/stellar/docs/pull/492 as suggested by @theaeolianmachine 
The goal is to avoid the use of JPEGs for logos in toml files by suggesting the use of certain file formats and transparent backgrounds. Mostly to make developers and especially designers lives easier when pulling images from toml files.
> Suggesting certain image types to include in toml file

- ecosystem/sep-0006.md
Clarify that jwt should always be in a header, and the only use case for query params should be in the case of the interactive webapp.
> [SEP6] Clarify jwt usage

- ecosystem/sep-0010.md
It is extremely important that the client in SEP10 verifies the transaction has a sequence number 0 so they don't accidentally sign a malicious transaction that can be sent to the blockchain.
> SEP10 Add client step to verify sequence number 0

- ecosystem/sep-0010.md
The verification of the challenge transaction is missing the check for sequence number zero.  The Utils function verifyChallengeTx mentions this in its comment, and verifies the seq number.
> Add additional check to sep10

- ecosystem/sep-0006.md
In the interactive flow, we should expect the amount to come from the interactive webapp, not the wallet.  This will be more clear if we can separate interactive and non-interactive into their own seps, but for now, give instruction on how to pass the amount back.
> [SEP6] Expect amount from interactive webapp

- ecosystem/sep-0006.md
* Anchors may support [SEP-12](sep-0012.md) customer info transfer if they need to handle KYC-ing customers
> SEP-12 is deprecated for a SEP-6 implementation.

- ecosystem/sep-0001.md
Need to standardize a max file size for stellar.toml so parsers can ensure they can handle any toml.  Context in https://github.com/stellar/stellar-protocol/issues/330
> [SEP1] Standardize max filesize

- ecosystem/README.md
Create a deprecated status and explain how to move a SEP into it.  Its important that we remove any cruft from our SEPs to ensure people have a clear understanding of the state of the ecosystem, and to prevent people from implementing SEPs that won't be compatible with anyone else.
> Add Deprecated status to SEP Process

- ecosystem/README.md
- sep-template.md
It is difficult to discuss proposals when there's no contact info for the authors.  Ideally we can just tag the authors using their github handle, but if for some reason they really don't want a github account we need to at least be able to email them.
> Require github handles

- ecosystem/README.md
- Modify the Final status to be one in which there are live implementations being used. Previously, Final and Active were too similar, and often misused. 
- Requires a Final SEP to have multiple implementations will give us much more confidence to mark something as final since we probably got most of the edge cases handled.
- Strongly suggests an Active SEP needs to have a reference implementation
> Update the definitions of Active and Final status

- ecosystem/README.md
- ecosystem/sep-0013.md
It seems that all of this functionality is now available in the non-interactive flow of SEP-6.  Is there anything missing that we should still consider from this sep?
@manran can you tag the other authors? They don't seem to be github handles.
> Reject SEP13

- ecosystem/sep-0006.md
For /withdraw and /deposit, we need to indicate that the error message is a string to be displayed to users, and also have a language option for localization.
Fixes #402
> SEP6 clarify error messaging

- ecosystem/sep-0006.md
They should not be optional, they're required for the expected UX of wallets
> [SEP6] Make transaction endpoints required

- ecosystem/sep-0024.md
Make it clear that more_info_url should always be returned.  I can't think of any cases where there shouldn't be a place to see info about your transaction.
> Make more_info_url non-optional

- ecosystem/sep-0024.md
The old sep6 had some stuff about passing email address from a wallet to an anchor.  This special case has been removed in favor of just supporting any SEP9 fields that the wallet may have.  It is useful to have the string `email address` there so that people can ctrl+f for `email` to find instructions on how to do this.
> Add email as an example of sep9

- ecosystem/sep-0011.md
Change `"NATIVE"` to `"native"` as the default string representation of the native asset.
The standard defines `"NATIVE"` to be the string representation of the native asset. In practice we use the lowercase string `"native"` in Horizon and in Ticker. While the specification does mention that any string up to 12 characters to be a valid reference to the native asset it is worth naming `"native"` explicitly since in practice is seems more in use.
> Change NATIVE to native

- ecosystem/sep-0002.md
Add recommendation for encoding phone numbers in federated addresses and tidy up the section that defines the requirements of usernames and domains.
We provide an example of how email addresses can be used in federated addresses which is helpful as it points out to services whose users usernames are their email address that the service can simply use that existing username as the username of the federated address without requiring their users to choose a new username.
Phone numbers are increasingly becoming the user identifiers of many services and it is possible a service will use a phone number as the username.
We should encourage a common uniform approach to encoding phone numbers into usernames using the recommended approaches from industry so that it becomes straight forward to query …
> Add recommendation for encoding phone numbers in federated addresses

- ecosystem/sep-0024.md
Making too many fields optional creates a large array of places where wallets and anchors can get out of sync.  There's no reason for most of these fields to be optional so lets just require them.
> Make optional fields required

- ecosystem/sep-0024.md
It was unclear if fee_fixed was additive with fee_percent, or if it was a minimum.  This adds `fee_minimum,` and clarifies that fixed+percent are additive.
Fixes #437
> [sep24] Add fee_minimum, clarify fees

- ecosystem/README.md
Currently we require some confusing SHA hash generation to submit a SEP proposal which seems overly confusing, so I replace it with just a short title of whats going on.
The important thing is just to have a unique name here, it will be changed to a number as soon as the draft is accepted (not finalized, just accepted as a draft).  I don't want to have barriers to entry to creating proposals
> Remove confusing sha stuff for sep submission

- ecosystem/sep-0002.md
Add `Updated` timestamp to the last date SEP-2 was updated, and a `Version` field, setting it to `1.1.0` assuming it has been updated once since its initial release.
In #428 I added instructions to the SEP for how to use a phone number as a username in a federated address. I missed adding an `Updated` timestamp when I made that change, and I've discovered reviewing other PRs that we do that normally.
I chose version `1.1.0` because there was no version field previously, but it is in `Final` status, so I assume if it hadn't had any major updates prior to now it was version `1.0.0`.
> SEP-2: Add updated timestamp and version

- core/cap-0025.md
Mainly to address a few simplifications that were added while implementing the CAP.
> CAP-0025 updates

- ecosystem/README.md
- ecosystem/sep-0003.md
according to [our docs](https://www.stellar.org/developers/guides/compliance-protocol.html) we don't recommend sep3 usage anymore and i don't know anyone who's actually implemented it.  Deprecate it now to avoid confusion in future.
> Deprecate SEP3

- ecosystem/sep-0024.md
Anchor/client interoperability is highly non-descriptive, this makes it clear that sep24 is for transferring assets
we can also let go of the fact that it's 'simplified' from sep6
> [SEP-24] Clarify Title

- ecosystem/sep-0024.md
Current recommendation for sending Personal Information like email address is via query params on the interactive URL.  Putting Personal info inside a URL is [a security risk](https://www.owasp.org/index.php/Information_exposure_through_query_strings_in_url).  This updates the protocol to send info via POST at the initial `/deposit` or `/withdraw` endpoints.  Anchors can then store this away to pre-populate in the interactive flow, and PII is never sent over URLs.
It's also more idiomatic since `GET /deposit` creates a new deposit ID, it should be a POST request since it has side effects.
It also changes the urls from `/deposit` to `/transactions/deposit/interactive` so people can keep running sep6 integrations.
This is the first non-backwards compatible change to SEP-6.
> [SEP24] Send PII over POST instead of GET

- ecosystem/sep-0010.md
Make really clear that the issuer is a URI and not a URL, and add notes about where to find best practices about JWTs.
It's really easy to see `URI` and just think `URL` even for us who are rather intimate with the SEP. An JWTs issuer can be a URL, but it also doesn't need to be, it can be a unique URI containing any information, such as the key used for signing. It is application specific and this clarification loosens the definition without prescribing how an application should populate the issuer field.
JWT best practices are important when implementing systems that use JWTs for authentication. It's out of scope for this SEP to capture those best practices, also because they are evolving, but we can link to the current best practices that the IETF are drafting.
> SEP-0010: Clarify best practices about JWTs and URIs

- ecosystem/sep-0024.md
One of the vestigial remains of the evolution of SEP6 is that the call to return the interactive URL should return as a `403 forbidden`.  This made sense when sep6 could be interactive or non-interactive and there were multiple ways to get through the flow, 403 was the closest thing to "More user info needed".  Given that this is now the one and only happy path we should probably cut the cord on this 403 response, and just show it as the correct response.
It would be good to land this at the same time as https://github.com/stellar/stellar-protocol/pull/438 since its already a breaking change regarding these endpoints, we can do it all at once.
> [SEP24] Remove the 403 forbidden stuff from the interactive endpoint

- ecosystem/sep-0010.md
Change use of `chose` to `choose`, and `it's` to `its`.
Incorrect spelling and use of apostrophe.
> SEP-0010: Fix grammar and typos

- ecosystem/sep-0010.md
Remove the `jti` as a required field on the JWT generated as part of SEP-10.
The `jti` is described in [RFC7519 Section 4.1.7] as being a unique identifier for a specific token that can be used to prevent a token from being replayed. In some situations it is desirable to only allow a token to be used one-time, even if it hasn't expired. While that might be a use-case of an anchor or other web service, it doesn't seem to be a core requirement of SEP-10. In fact SEP-10 uses a JWT as a way of getting a reusable token from a challenge-response that is not easily reused, so repeatable use of the JWT is anticipated.
Motivation for removing this now is that we are exploring other SEPs that build on SEP-10 and involve augmenting an existing JWT and issuing a new JWT that includes additional …
> SEP-0010: Remove the jti as a required token field

- ecosystem/sep-0024.md
Better describes how wallets should use the more_info_url to also show banking information (for deposits) after the interactive flow is complete.
> Update SEP-24 description of the more_info_url parameter

- ecosystem/sep-0024.md
To make it a bit clearer how to update from SEP-6 to SEP-24 i list the changes at the bottom of the document.
I also brought the `account` parameter of the `/transactions` endpoint back.  In the case of a delegated signing situation where you are authenticating with a Signer account, we can't actually pull the account in question from the JWT.
> Add sep-6 to sep-24 instructions

- ecosystem/sep-0024.md
Clarify that the /info endpoint, which provides publicly accessible information, shouldn't require an auth token, but all other endpoints should.
> [SEP24] Don't require auth for /info

- ecosystem/sep-0010.md
Add requirements to SEP-10 that a server validate that the client key that has signed the challenge transaction is actually a signer of the account. Add details about how multiple signatures on a challenge transaction are a possibility.
SEP-10 has the goal to provide the mechanics to help a server get proof that a client holds a Stellar account, but if a server was to implement only the functionality described in this document it would only be proving that the client is in possession of the secret key of the account's address, the master key, and not necessarily the Stellar account. The checks required to go beyond that have until now been left up to the implementer to define.
Proving possession of a secret key doesn't prove any threshold of control of an account because an account can …
> SEP-10: Add multi-sig capabilities

- ecosystem/sep-0011.md
Add headings to the Values section of the document with each type and unique encoding situation getting a heading.
I find myself frequently needing to link to sections in this document, specifically the section about how to encode `Asset` as a string. Without headings it is not possible to link directly to the discussion about the `Asset` type and I can only instead link people to the section about values and hope that they read through to find what I'm referencing. It makes it easier to share concepts and behaviors defined in this SEP if they can be easily linked to.
> SEP-0011: Add headings to values sections

- ecosystem/sep-0024.md
Since sep24 now uses a completely separate endpoint from sep6 we no longer need to add this confusing note about ignoring sep6 responses.
> [SEP24] remove vestigial note about sep6

- ecosystem/sep-0018.md
Distill SEP-18 to focus solely on namespace syntax and definition, and
leave parsing and interpretation of, parsing, and rendering of a set of
data entries to applications and/or a future SEP.
The main gains we get from @MisterTicot's SEP-18 immediately is for
other SEPs to define data entries that do not collide with other
applications by placing them in a namespace that other applications know
should be avoided. The SEP also attempts to define how to parse the data
entries into trees, but this can be implemented in many different ways
and has unique challenges that deserve being the focus of their own SEP.
It should be quite easy to build another SEP on-top of SEP-18.
@MisterTicot @orbitlens @tomerweller @tomquisel
> SEP-0018: Distill down to focus on namespace syntax and definition

- ecosystem/sep-0011.md
Break up the paragraph about assets, with the two forms that an asset can be rendered in being listed as dot points.
The paragraph is pretty big and you need to dig into it to identify what the most important parts are to find the different forms of rendering.
Breaking the paragraph up makes it easy to glance, see that there are two forms, and to skip past the additional details that for the most part are only relevant to debugging.
> SEP-0011: Break up the paragraph about Assets

- core/cap-0023.md
@jonjove I think the reserve should just be `claimants.size() * baseReserve`, but please close this out if I missed something.
> Minor reserve logic fix, CreateClaimableBalanceOp

- ecosystem/sep-0024.md
We removed the way for anchors to request user data from wallets now that this should all be collected during the interactive flow, but this was never documented in the 'changes from sep6' section.
> [SEP24] Document missing sep6 changes

- ecosystem/sep-0001.md
- ecosystem/sep-0024.md
Add "TRANSFER_SERVER_SEP0024" to the SEP-1 Account Information fields. This can be used by wallets to differentiate between anchors (or on/off ramps) that implement SEP-0006 and SEP-0024.
> [SEP-1] Add SEP-24 Transfer Server Field

- README.md
Update CAP/SEP buttons to link to their READMEs.
For the longest time I didn't realize the README's exist, because I'd go to each directory and have more than a screen's worth of files displayed above the page fold. I think surfacing the READMEs as the primary place to go will help newcomers because those READMEs organize the CAPs/SEPs into accepted vs drafts which is really helpful when first arriving at the repo.
> README: Update CAP/SEP buttons to link to their READMEs

- ecosystem/sep-0030.md
Add a proposal for recoverysigner, multi-party key management of Stellar accounts where no server managing keys has control of the account, and supporting users:
1. Recovering access to Stellar accounts for which they may have lost keys.
2. Gaining access to Stellar accounts that another user intends to share with them.
I have been experimenting with this proposal in implementation first over in the [exp/services/recoverysigner] package which implements most of what is documented here. I think I've experimented enough with it to warrant documenting.
I expect this proposal to remain in draft state for sometime while the finer details of the SEP are ironed out. I'd like to merge the SEP without perfecting it so that I can iterate on it, and keep it and the experimental implementation in …
> SEP-0030: Add proposal for recoverysigner multi-party key management

- ecosystem/sep-0030.md
Remove the statement about the order of the results that are returned by
the `GET /accounts` endpoint.
Ordering by when the accounts were registered is not of significance
since no fields about the registration time are included in the response
and there is nothing that we can imagine right now that a client would
do with that information. We should limit the SEPs requirements to those
that matter.
> SEP-0030: Be less prescriptive about order of pagination

- ecosystem/sep-0010.md
Add information about why the network_passphrase field is provided in
the response.
On a quick read of the docs readers have assumed the presence of the
network_passphrase field is for the server to tell the client which
passphrase to use. While there may be valid uses of the field in that
way the intention for why the field was added was to be a debugging
mechanism so that it is immediately clear if a client or server as
misconfigured. The reason this is helpful in that situation is because
the network passphrase affects the signature of the transaction but is
not stored in the transaction, so if a client or server are configured
incorrectly the error message from the server when verifying the
transaction will simply be that the signature is invalid.
This change is not a breaking change …
> SEP-0010: Add info about why network_passphrase is included

- core/README.md
- core/cap-0013.md
This seems to be superceded by CAP23, moving this to rejected to prevent confusion
> Reject cap13

- README.md
Update the URL for the Stellar logo image displayed at the top of the
README.
A new version of the stellar.org website was deployed and the image we
were using is no longer available there. In stellar/.github#9 we added
the logo to a GitHub repository so that we could reference it from one
location that won't be affected by website changes.
> README: Fix Stellar logo image

- ecosystem/sep-0030.md
Change the fixed set of identities to be a list and make the roles arbitrary strings rather than a fixed set.
To allow for easier expansion in the future of both additional roles, multiple identities per role, and multiple values for each identity type (email, phone, etc).
> SEP-0030: Change the list of identities to be an arbitrary list

- ecosystem/sep-0030.md
State what transactions will be signed by a SEP-30 server.
It isn't clear exactly what transactions a SEP-30 server will sign. The document states that transactions for an account will be signed, but we should be more explicit about what that means.
This is a follow up to https://github.com/stellar/stellar-protocol/pull/566#discussion_r392453939.
> SEP-0030: Make what transactions can be signed clearer

- ecosystem/sep-0024.md
Expand the scope of the `lang` param when starting a transaction.  This can also be used to localize the interactive flow UI, as well as anything else that might be shown to the user in the context of this transaction
> [SEP24] Update lang param description

- ecosystem/sep-0010.md
Add notes to the Abstract section about the optional behavior with Stellar accounts that do not yet exist.
This behavior is already detailed in the section that describes the behavior of the server when handling the Token endpoint. This is not new behavior, but not mentioning the behavior in the abstract has led to some confusion because a reader who only reads the abstract will think that an account must exist to be compatible with SEP-10.
The version bump as a patch number is due to no functional changes to the proposal.
> SEP-0010: Note behavior for non-existent accounts in Abstract

- ecosystem/sep-0001.md
This is a minor cosmetic change to put the version field in a more prominent location in the spec and in the example
> Make the VERSION field more prominent

- ecosystem/sep-0026.md
Make large example responses collapsible using `<details>`/`<summary>` elements. The doc as of now looks super intimidating, even to SEP-6 / SEP-24 veterans. This should make it much easier to keep an overview.
[**Before**](https://github.com/stellar/stellar-protocol/blob/fcc397b6cc3dbbeb3ef44323581395322e907816/ecosystem/sep-0026.md) • [**After**](https://github.com/andywer/stellar-protocol/blob/sep-26/make-easier-to-read/ecosystem/sep-0026.md)
Related to #484.
> SEP-26 - Make document easier to read

- ecosystem/sep-0024.md
To make a nice UX many wallets wish to collect the amount of deposit/withdrawal ahead of time to show fees before going through the whole interactive process.  We had originally loosely suggested providing it to the interactive url, but that doesn't help calculate fees ahead of time, and wasn't well documented.  Here we add it to the params expected in the initial POST calls.
> [SEP24] Add explicit amount field to api

- ecosystem/sep-0001.md
- ecosystem/sep-0024.md
Fixes #443 
Adds an asset_issuer field to the initial POST requests when creating a transaction.  This serves 2 purposes:
1. Allows anchors to deposit/withdraw assets they didn't issue
1. Allows deposit/withdraw of lumens
It also changes the definition of asset_code to refer to the stellar asset for deposit as well as withdrawal, instead of being different for deposit and withdrawal.  This was a subtle difference that caused a lot of confusion.
> [sep24] Add asset_issuer

- ecosystem/sep-0029.md
If there as a payment operation where the destination address is a muxed account with a memo id, then we should not perform the SEP29 check on the destination account. A muxed account with a memo id essentially encodes a memo within the account's address. There is no point in requiring clients to provide a memo when sending payments to a multiplexed account.
> Update SEP-29 to handle muxed accounts

- ecosystem/sep-0030.md
Add endpoints to support rotating signing keys.
In any systems with keys it is important to support rotating those keys.
Keys may need rotating for many reasons including:
- Routine best practice.
- In response to a key being leaked.
- In response to a key being compromised.
- As a requirement to meet a compliance standard.
cc @stellar/vega-backend
> SEP-0030: Add support for rotating signing keys

- ecosystem/sep-0030.md
Remove the /sign endpoint and the `signer` field in the common account response.
The endpoint and field were marked as deprecated in v0.3.0. They make less sense in the new version of SEP-30 where the client selects a signer and in the interest of keeping the API as simple as possible and encourage clients to choose a signer these should be removed. Breaking changes are possible because this SEP is still in draft and the breaking changes were separated out from v0.3.0 to make the proposed change clearer for implementations based on the draft to navigate the change.
> SEP-0030: Remove deprecated fields and endpoint deprecated in v0.3.0

- ecosystem/sep-0024.md
resolves stellar/django-polaris#190
This PR is a result of the discussion at stellar/stellar-protocol#625
Removes mentions of the ability to 'anchor' XLM. This functionality should be more thoroughly discussed to ensure there is sufficient ecosystem demand and a solution that doesn't involve adding exceptions or special-cases to an existing SEP.
> SEP-24: Remove XLM anchoring clauses

- core/cap-0027.md
- ecosystem/sep-0006.md
- ecosystem/sep-0007.md
- ecosystem/sep-0008.md
- ecosystem/sep-0024.md
- ecosystem/sep-0026.md
Remove use of the terms whitelist and blacklist, replacing them with other descriptions of what functionality is intended or with other terms allowlist and denylist.
The terms whitelist and blacklist make many people feel unwelcome and can trigger racial stereotyping. A similar change was made on the Go repository which prompted me to check if we used these terms in our documentation or code. golang/go@608cdcaede1e7133dc994b5e8894272c2dce744b
The terms whitelist and blacklist are not better at communicating intent than simply describing the behavior we're looking for or than using another term. This seems like an easy change to make with no cost that improves the general language of our documentation. An example of how this generally improves the documentation is this sentence where we …
> ALL: Remove use of the terms whitelist/blacklist

- ecosystem/sep-0031.md
These changes are not strictly necessary because SEP31 requires the 2 participating anchors to come to an agreement prior to facilitating transactions on behalf of their users. This agreement would presumably include a list of acceptable assets and their respective issuers.
However, it is better for the receiving anchor to reject `/send` requests when they made rather than having to refund payments of an unaccepted asset. It also allows receiving anchors to create transaction records in their database including the asset expected.
> SEP31: Add asset_code and asset_issuer to /send request parameters

- ecosystem/sep-0018.md
Defines a few canonical namespaces. The general idea is that root namespaces are tied to a function while child namespace may be tied to a scope, similarly to `/etc`, `/home` & `/lib` in Unix systems.
`profile` & `wallet` are not being used yet but are mentioned in case someone need them for future SEP.
> SEP-0018: Add canonical paths & restrictions

- ecosystem/sep-0030.md
Remove the `added_at` field from signers.
The field adds a burden on the implementer to keep track of when a signing key is generated and stored but without any substantial value to the client.
Servers that use shared signing keys are likely to store and configure their signing keys through systems that don't store metadata like time alongside them. For example if a key is simply stored as a secret in their deployment system it may not have a time. In our reference implementation this has resulted in us returning a zero time in some cases.
We originally included the field on the assumption that a client may like to know when a key became available. In practice however that information is irrelevant to a client. A client, especially used by a consumer, isn't going to display the time the …
> SEP-0030: Remove the added_at field from signers

- ecosystem/sep-0031.md
`require_receiver_info` is a controversial feature of SEP31.  It is used when a sending anchor requires information about a receiving client, and assumes the receiving anchor can fetch that information from their banking rails or other source, and can legally share it with them.  
Given that no one has a hard requirement for it right now, and it seems unlikely too many anchors will have this capability or want to share this kind of user info, I propose we remove this until someone actually has a pressing need for it, then we can put it back.
> SEP31 - Remove require_receiver_info

- ecosystem/sep-0030.md
Add security section about external authentication methods and highlighting that a SEP-30 implementation chooses what external authentication methods to support and clients choose which to use when registering accounts.
The intention is that the external authentication methods are flexible and the methods use make sense for the use case, both functionally, and from the perspective of security and risk. The document already takes this position but this section clarifies that intent. 
cc @capybaraz @accordeiro
> SEP-0030: Add security section about external authentication methods

- ecosystem/sep-0031.md
All our other SEPs use 403 to represent a request that hasn't been authorized with sep10.  Technically, 401 is more accurate but 403 seems to be widely used as an unauthorized request response code, so I don't think there's any reason to complicate implementation details.
> SEP31: Use 403 for unauthenticated requests instead of 401

- ecosystem/README.md
Add SEP-31 to the ecosystem README's list of Active SEPs.
The SEP is missing from the list but exists in the repo.
> SEP-0031: Add to ecosystem README list of Active SEPs

- core/cap-0023.md
This PR contains a couple clarifications, along with a slightly stricter check for the `andPredicate` and `orPredicate` size. No value other than 2 makes sense here, so `!=` is clearer than using `<`.
> CAP-0023 clarifications

- ecosystem/sep-0012.md
resolves stellar/integration-meta#146
Many anchors need the ability to KYC customers ahead of time, before doing any transactions with them.  This is especially important for B2B where kyc is manual and takes a while.  SEP-12 starts to provide this, but is underpowered, particularly in that the client has no understanding of what the anchor requires for KYC, or what additional fields it might need, it only has the ability to send fields blindly.
This adds a `GET /customer` method in order to check the status of an existing users KYC, or to find out what fields are needed to KYC a new user, or complete an in progress KYC attempt.
Discussion here: https://docs.google.com/document/d/1LuTKU5E_cOgQYlWBUol1dwUVO5FrVpUE4XZSXRuoNqA/edit
> [SEP12] Add GET method for customers

- ecosystem/sep-0031.md
resolves stellar/integration-meta#147
Added the ability to use SEP-12 for KYC'ing senders and receivers of SEP-31 transactions.
- Changes the format of the `GET /info` response to include `sender_sep12_type` and `receiver_sep12_type`
- Removed fields other than `memo` in the `sender` and `receiver` objects for `GET /info` and `POST /send`
- Changed the `customer_info_needed` error response to signal a required update to the SEP-12 `PUT /customer` endpoint
- Renamed the original `customer_info_needed` error response to `transaction_info_needed`
- Changed `pending_info_update` `Transaction` status to `pending_transaction_info_update`
- Added `pending_customer_info_update` `Transaction` status for updates to SEP-12 `PUT /customer`
> SEP31: Added SEP-12 logic

- ecosystem/sep-0031.md
Forgot to do this in the initial SEP-12 changes PR.
> SEP31: Moved 'sender_id' and 'receiver_id' outside of 'fields' in /send request

- ecosystem/sep-0031.md
[SEP-12](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0012.md#customer-put)'s documentation specifies that the `id` returned from `PUT /customer` can be a string or integer.
We also need to clarify that the SEP-12 args like `sender_sep12_type` and `sender_id` are optional, since the anchor may not require KYC for the sender, or even the receiver.
> SEP-31: Small changes for SEP-12 compatibility

- core/README.md
- core/cap-0034.md
First draft of CAP-0034, intended to address
stellar-protocol issue #622, by changing the semantics of
the combination of candidates by the SCP ballot protocol
from producing an unsigned form of union of the candidates
(taking, for example, the maximum closetime of all
candidates as the closetime to externalize) to selecting one
particular signed, nominated StellarValue (comprising
transaction set, closetime, and upgrades) as the one to
externalize.
See also the [draft implementation](https://github.com/rokopt/stellar-core/tree/proto-622-closetime).
> Draft of CAP-0034 (change closetime semantics)

- ecosystem/sep-0024.md
Without a home_domain, a wallet has no way to find the toml file needed to start the SEP24 process.  While this instruction is mentioned in the SEP1 documentation it's very easily missed.  This is exacerbated by the fact that our tools let you plug the toml file in directly which makes it seem like you don't actually need the  home domain.
> SEP24: Add home_domain instructions

- ecosystem/sep-0001.md
The SEP lists the accounts `home_domain` property as `homedomain`.  This is important to fix because its not googleable if someone wants to find where we talk about `home_domain`
> SEP1: properly name home_domain

- core/cap-0023.md
Return the `balanceID` if `CreateClaimableBalanceOp` succeeds. This will make claimable balances easier to use since the user of the operation can use the result instead of deriving the `balanceID` from the transaction.
> CAP-0023 - return balanceID on successful CreateClaimableBalanceOp

- ecosystem/sep-0007.md
In my opinion, if `memo` exists in the URI, `memo_type` should also exist. 
If I miss something, please point out.
Thank you.
> SEP-0007: fix example Stellar URI.

- core/cap-0034.md
- Make the effect of the proposal on
`minTime`/`txTOO_EARLY` validation explicit; formerly it
had mentioned only `maxTime`/`txTOO_LATE`.  Point out that
the change makes the nomination and ballot protocols use
the exact same `closeTime`-related conditions to trim and
validate transactions as the externalization (ledger close)
code does.
- Incorporate further code review comments to correct and
clarify several pieces of SCP-related wording and
presentation.
- Correct "maximal `closeTime` injection" sections to
explain the attack and the degree of amelioration more
accurately.
- Clean up confusing (and in at least one place, just
wrong) section #4 of "Detailed argument in favor".
- Remove misleading references to transaction sets or
`StellarValue`s "winning"; specify that it is being …
> Third draft of CAP-0034 document

- ecosystem/sep-0031.md
This pull-request updates the URL schema for transactions to make it look more like a resource rather than use custom URLs for different interactions with the same resource. It also makes it more clear how to collect/update a given resource.
The following are the changes included in this PR and the rationale behind:
1. Pluralize resource URL to `/transactions`: this could look more like bikeshedding but since I was going to propose a change on the URL schema I went for plural, keeping the doors open to eventually allow a new end-point to query transactions in bulk.
2. Change `GET /transaction` to `GET /transactions/:id`: The current SEP is not clear on how the `ID` should be pass is it in the URL is it as a query param? This change makes it explicit that the resource ID should be pass as …
> [SEP31] Update URL schema for transactions and replace update HTTP method with a PATCH.

- ecosystem/sep-0031.md
This is a follow up on https://github.com/stellar/stellar-protocol/pull/692 -- the proposal is to create new transactions through a `POST` request on `/transactions`.
This PR also updates the response code to a 201, meaning a new transaction has been created and can be processed.
> [SEP31] Change URL end-point to create a new transactions.

- ecosystem/sep-0031.md
I deleted this key from the request, but it is part of the transaction resource and that's what the request is patching.
> [SEP31] Put back fields in patch request to transaction.

- ecosystem/sep-0012.md
resolves stellar/stellar-protocol#704
`GET /customer` allows clients to specify the `id` returned when creating the customer via the `PUT` method. This change allows anchors to update existing customers using the same argument on `PUT /customer`.
> SEP-12: Added 'id' param to PUT /customer

- ecosystem/sep-0024.md
A one-time token is a more secure approach.
> SEP-24: Remove mention of short-lived token as acceptable

- ecosystem/sep-0010.md
resolves stellar/integration-meta#180
Makes a SEP-10 service's `SIGNING_KEY` required in their stellar.toml file. Also changes the value of the manage data operation from a random 64-bit value to the service's home domain.
If the home domain specified in the manage data operation doesn't match the home domain request by the client, or the `SIGNING_KEY` specified on the TOML file did not sign the transaction, the challenge is invalid and the client should not sign it.
> SEP-10: Make SIGNING_KEY required and change manage data op value

- ecosystem/sep-0012.md
This PR adds a 404 response to the `GET /customer` endpoint which should be used when the `id` passed is for a nonexistent customer or for a customer created by another anchor, determined by the `sub` JWT key.
This response code will allow clients to determine if a customer exists as opposed to getting 400 back, which could mean the request was bad.
> SEP-12: added 404 response to SEP-12 GET /customer

- ecosystem/sep-0001.md
Is `DIRECT_PAYMENT_SERVER` the way we want to go? Its assumed in Polaris, but thats the only released software that uses it currently.
> Add SEP-31's DIRECT_PAYMENT_SERVER attribute to the TOML attribute list

- ecosystem/sep-0010.md
Revert home domain verification and relax manage data operation constraints allowing additional manage data operations as long as their source account is the server account.
There's been some ambiguity about the intended contents of home domain and in the interest of encouraging compatibility between servers and clients I think we need to consider reverting verification the SEP and SDKs are requiring on that field.
The relaxing of the manage data operations so that we can add a new manage data operation in <SEP-10 v3.0.0 PR> that adds a new hostname for verification. Allowing additional manage data operations with the server account as the source account will allow future releases to add additional fields of data without breaking older clients. Requiring the source account to be the …
> SEP-0010: Revert home domain verification and relax manage data operation constraints (v2.1.0)

- ecosystem/sep-0030.md
Allow SEP-30 servers to sign transactions that contain source accounts other than the authenticated account, at the discretion of the SEP-30 server operator.
SEP-30 is not compatible with CAP-33 because SEP-30 requires servers to reject transactions that contain other accounts as source accounts. For accounts that have signers sponsored by a sponsoring account as supported by CAP-33, changing a sponsor requires operations with the sponsoring account as a source account. This means it is not possible to change a sponsored signer via a SEP-30 server.
The limitation within SEP-30 is to address the confused deputy problem. The SEP-30 server is signing a transaction, potentially with a shared key, and it must ensure that it only signs a transaction for a user that relate to accounts that the …
> SEP-0030: Make compatible with CAP-33

- ecosystem/sep-0012.md
Ensures readers do not think `id` is required.
> SEP-12: Clarify optional nature of 'id' parameter for PUT /customer

- ecosystem/sep-0010.md
Clarify that the first manage data operation is the operation containing the client account, nonce, and home domain.
The first manage data operation has always been the first operation. This is stated explicitly further down in the SEP when the challenge transaction structure is described. All SDKs I have reviewed also follow this pattern. The abstract is somewhat ambiguous though because it states that there is a single manage data operation with those values without stating it is the first.
This change is in response to the discussion here:
https://github.com/stellar/stellar-protocol/pull/746#discussion_r509686786
This change is only improving the language and is not adding or changing the functionality of the SEP. This change is not urgent and may end up being merged before or after …
> SEP-0010: Clarify the first manage data operation is the operation containing the client account, home domain, etc

- ecosystem/sep-0012.md
Remove mentions of SEP-6 from the summary and mention other SEPs that use SEP-12 instead of only SEP-6.
On a first read of it's easy for someone without context to think that SEP-12 is only intended for use with SEP-6, but it is intended to be used for any data collection that other SEPs might need to do with an authenticated user.
> SEP-0012: Make less about SEP-6

- ecosystem/sep-0032.md
Make it explicit that if a home domain is not set for an issuer account the reverse resolution fails.
This is implied but not explicit leaving an unanswered question to the reader about what a client should do if the client is using the reverse resolution for verification.
This was highlighted by @pitsevich. Thank you!
> SEP-0032: Make explicit that a missing home domain fails reverse resolution

- ecosystem/sep-0030.md
Change the title to `Account Recovery` and remove mention of key management in title.
The SEPs purpose is to provide a multi-party approach to recovering Stellar accounts, either accounts a user created or owns, or accounts that another user has created and shared with the user. It is not technically key management because it is an interoperability layer that sits in the middle of an approach to key management.
The title `Recoverysigner` has also not been very useful. It was added to the beginning of the title to provide a single word keyword that could be used to reference SEP-30, but it turns out the term is odd, and so isn't being used to reference SEP-30.
> SEP-0030: Change title to Account Recovery

- ecosystem/sep-0010.md
Add back the home domain verification, but with greater clarity about exactly what the home domain is.
In v2.1.0 the home domain verification that was added in v2.0.0 was removed because the exact contents of the home domain field could be interpreted in at least two different ways that led to inconsistent implementations. The home domain is still present in the SEP-10 challenge transaction and this change provides clarity to what it should contain and how clients should verify it. This change represents the intended understanding of the home domain field. See v2.0.0 and v2.1.0 for prior context.
Servers should use this change to verify that they are placing the correct value for the home domain into the challenge transaction. Once clients implement v3.0.0 they will reject challenge …
> SEP-0010: Add back home domain verification with clarity (v3.0.0)

- ecosystem/sep-0030.md
Add clearer instruction that other authentication types are supported and recommended formats for their use.
SEP-30 has always stated that implementers may choose any authentication methods, and there are no limitations within SEP-30 that require an authentication method to be synchronous and immediate. However this has not been clear as the SEP only discusses phone and email authentication in any real detail.
This change does not yet improve interoperability when other authentication methods are used because the formats for those authentication methods are not yet defined. I'll follow up with that in separate PRs.
Note: SEP-30 has other issues regarding interoperability in that external authentication is not defined in anyway within this SEP, however this change does not address that and …
> SEP-0030: Add clearer instruction that other authentication types are supported

- ecosystem/sep-0030.md
Remove mention of async/sync authentication methods and replace it with a more concise list of example authentication methods.
@JakeUrban pointed out in https://github.com/stellar/stellar-protocol/pull/765#pullrequestreview-531948828 that the section we have here that is being changed focuses on the authentication methods being synchronous or asynchronous and that is not particularly helpful to an integrator. The change in this change refocus the paragraph on what the external authentication can be which is more meaningful.
> SEP-0030: Remove mention of async/sync authentication methods

- ecosystem/sep-0030.md
Be unopinionated about number of servers required by protocol and do not exclude use of the protocol with a single server, but include note that the single server configuration means control of the account.
The protocol specifies an interface a client and server can use to facilitate account recovery through transaction signing and authentication with providers outside of the Stellar network. It supports a configuration where a client uses multiple servers so that no individual server has control of the account on its own, but that is one use case and the protocol can support being used with a client and server configuration where there is only one server. There is little reason to limit the SEP to only multiple servers as it is up to the client how many servers they integrate with and …
> SEP-0030: Be unopinionated about number of servers required by protocol

- ecosystem/sep-0024.md
Wallets need visibility into the user's KYC status to alert users when they can continue or re-request their deposit / withdrawal intent after being approved. This adds two things that help do this:
- A boolean `kyc_verified` field on transaction objects
- A `on_change_callback` that calls back each time the transaction object's `status` or `kyc_verified` fields change
> SEP-24: Communicate KYC status

- ecosystem/sep-0008.md
**What**
Update the status of SEP-8 from Final to Active.
**Why**
The current SEP-8 was introduced before CAP-18. The practice we advertise in SEP-8 can be improved with the new protocol support. There are active developments of transacting regulated assets in the ecosystem that surfaces the need to keep SEP-8 up-to-date.
The definitions of Active and Final have not historically been followed, so SEPs created a little while ago may have progressed quicker to Final than newer SEPs have. And It appears that SEP-8 was finalized sooner than it's supposed to be. At this point, due to the ongoing developments, deprecating this SEP and creating a new SEP to replace the current one can create unnecessary noises. As a result, we decided to switch the status of this SEP back to Active in order to …
> SEP-8: update status to Active

- ecosystem/sep-0010.md
Changes the `home_domain` parameter in the SEP-10 `GET` endpoint to reference the definition of "the home domain" in the abstract.
> Replace ambiguous home domain parameter definition

- ecosystem/sep-0024.md
resolves #558 
Updates the SEP-24 encoding policy to match SEP-30 and other more recent SEPs.
This same change in spirit is being made to the following SEPs:
- SEP-12 (#789)
- SEP-31 (#790)
SEP-6 doesn't need to specify an encoding policy because all requests are `GET` requests.
An exception to this emerging standard is SEP-12, which supports sending file data, and `multipart/form-data` is a common encoding used for file uploads. SEP-6 and SEP-31 will be updated to use the same encodings as SEP-24 and SEP-30, while SEP-12 requests will continue using `multipart/form-data`.
> SEP-24: Update request/response encoding policy to match SEP-30 and others

- ecosystem/sep-0012.md
- ecosystem/sep-0031.md
relates to #788 
Adds a `Content-Type` section to outline what encodings are accepted for requests and responses. SEP-12 differs from most standards by supporting `multipart/form-data` since requests could contain file uploads.
> SEP-12: Added Content-Type policy section

- ecosystem/sep-0006.md
resolves #785 
SEP-6 was originally created to support both interactive and non-interactive flows for deposits and withdrawals. SEP-24 was then created and offered an interactive-only protocol, and the interactive portions in SEP-6 were deprecated.
At this point, there is no reason to keep the interactive portions in SEP-6 at all. Removing these sections will make the protocol more focused and reduce potential for confusion.
No functional changes to the protocol were made, but I did rewrite the `Transaction Polling` section which originally asked clients to use transaction IDs in order to fetch a transaction's current status. The problem with this suggestion was that IDs are not return for non-interactive responses. Hence the only way to match a transaction is to use the memo's specified …
> SEP-6: Remove all interactive portions

- cap-template.md
Add semantic section to CAP template within the specification section.
I've noticed that in many of the CAPs that are authored by @jonjove the CAP separates the XDR definitions from the semantics of how those new or changed XDR types function. This template was recently updated. It's not clear to me if the semantics section was intentionally left out with the intention to discuss the semantics within the XDR section, or if it was accidental. I suspect it was accidental because otherwise there would be little reason to have the XDR sub-section of specification.
> Add semantic section to CAP Template

- core/cap-0035.md
Move XDRs into a single section and move discussion to a semantics section.
To adhere to the CAP template. No functional changes to the CAP.
> CAP-0035: Move XDRs into a single section and move discussion to a semantics section

- core/cap-0035.md
Address concerns raised by Jon and Nicolas on the [mailing list](https://groups.google.com/g/stellar-dev/c/hPhkXhrl5-Y/m/ZF6eJcqKAgAJ?pli=1).
Specifically:
- Remove `AUTH_CLAWBACKWABLE` and use `AUTH_REVOCABLE`.
- Change what happens when the `CallbackOp` is used on an account that has selling liabilities such that it functions like other operations and fails.
- Include an example of how to use `AllowTrustOp` to temporarily revoke authorization of an account to free up selling liabilities.
- Include discussion highlighting how the limitations of clawback match the limitations of revoking authorization, and how they cannot affect claimable balances.
- Include discussion about backwards compatibility.
- Include discussion about thresholds.
Addressing feedback from the [discussion …
> CAP-0035: Address concerns raised by Jon and Nicolas on the mailing list

- core/cap-0035.md
Add note about how issuers can prevent creation of claimable balances.
@MonsieurNicolas identified [on the mailing list](https://groups.google.com/g/stellar-dev/c/hPhkXhrl5-Y/m/l2OTWiKSAQAJ) that `AUTHORIZED_TO_MAINTAIN_LIABILITIES_FLAG` introduced in CAP-18 and SEP-8 could be used by a regulated asset issuer to restrict the creation of claimable balances.
> CAP-0035: Add note about how issuers can prevent creation of claimable balances

- ecosystem/sep-0009.md
Add `bank_branch` field to Natural Person KYC fields in order to identify customer's bank branch number wich is needed in Brazil, for example.
> SEP-9: Add bank branch field

- ecosystem/sep-0024.md
resolves #771 
Currently, the anchor is instructed to not list the minimum funding amount (2.01XLM recommended) as a fee because the user still receives that amount in their account. While true, the user cannot transact that minimum funding amount, due to it being the _minimum amount the account needs to exist_.
Its also in the anchors best interest to sponsor account creations, so deducting the minimum funding amount from the deposit given to the anchor likely brings more complexity and UX dissatisfaction than its worth.
> Clarify SEP-24 account funding policy (special case)

- ecosystem/sep-0008.md
**What**
This PR beautifies and re-formats SEP-8 without changing the functionality. It also makes things clear by adding a section "authorization flags" in order to explain how to identify a regulated asset in the first place. Finally, account setup is removed from `Overview` because it's not necessary. However, this PR does not remove the `Account Setup` section as its goal is to improves readability.
**Why**
A portion of the content and format in SEP-8 is outdated as it was created more than 2 years ago.
> SEP-8: reformat

- ecosystem/sep-0006.md
resolves #809 
Mirrored the changes made in #798 word-for-word. This change clarifies how anchors should handle deposit requests to accounts that do not yet exist or have insufficient XLM for adding a trustline to the requested asset.
> SEP-6: Mirrored change from #798

- ecosystem/sep-0012.md
The `GET /customer` endpoint has an optional `message` response attribute that is currently implied to only be used for rejection responses. However, SEP-6/SEP-31 Wallets may want to display a human readable message to their users while KYC information is being processed instead of opening a `more_info_url` from the anchor.
> SEP-12: Allow GET /customer in PROCESSING to have 'message'

- ecosystem/sep-0008.md
**What**
Support JSON encoded request.
**Why**
We accept the `application/json` content type in some other SEPs, e.g. SEP-10 and SEP-30. The viewpoint from some people outside SDF that led to this pattern on SEP-10 was that it makes it easier to integrate with the APIs in some cases.
**Note**
This PR would have a version conflict with https://github.com/stellar/stellar-protocol/pull/817. One that gets merged first will have version 1.1.1; one that gets merged later will have version 1.2.1.
> SEP-8: add application/json as request content type

- ecosystem/sep-0008.md
**What**
This PR replaces Account Setup with Transaction Composition.
**Why**
SEP-8 was introduced before CAP-18 was introduced. The Account Setup section in the current SEP-8 has a few drawbacks as mentioned in CAP-18.
```
1. The owner of an account cannot unilaterally utilize assets unrelated to the issuer without the signature of that issuer
2. If multiple issuers want to become signers on a single account, then many signatures are potentially required for simple operations
3. Issuers cannot easily rotate keys, because their keys are on every account holding their asset
```
We are seeing a few active developments on regulated assets in the ecosystem, and we want to make sure the associated SEP is up-to-date and is easy to use without introducing breaking changes.
**Note**
This PR would …
> SEP-8: replace account setup with transaction composition

- ecosystem/sep-0008.md
**What**
Make `0` timeout mean that the issuer could not determine the timeout needed. 
**Why**
Issuers sometimes need to take extra steps before approving a transaction. Those steps may require manual actions.
In order to avoid breaking changes, we can use `0` to indicate the case where issuers couldn't determine the timeout at the time of returning the response. If we don't add this note, it can be misleading as `0` time might as well mean that the wallet/user can re-submit the transaction immediately.
> SEP-8: add meaning to zero timeout in the case of pending

- ecosystem/sep-0030.md
Remove urlencoded form data as a accepted content-type in requests.
@JakeUrban pointed out how there is really no consistent standard for encoding complex nested data in urlencoded form, which means that integrations are highly likely to use it, or to be buggy. We started using dual content types in requests in SEP-10 and we applied that broadly here but the difficulty to use is compelling that this isn't going to have a positive return on investment to maintain and isn't a pattern we should propogate to other SEPs either.
Related conversation in https://github.com/stellar/stellar-protocol/pull/790.
This change is breaking but the proposal is in draft and that is acceptable. It is also unlikely that there are implementations using form encoding given the difficult to provide that feature. …
> SEP-0030: Remove urlencoded form data as an accepted content-type in requests

- core/cap-0035.md
Store a snapshot of the state of whether a trustline is clawbackable in the trustline itself, rather than storing it only in the account. Also, add a new operation for clawing back claimable balances.
These changes are based on the proposal by @sisuresh [here](https://groups.google.com/g/stellar-dev/c/hPhkXhrl5-Y/m/UFJsWcdqCQAJ), but the inclusion of a separate operation is an idea @jonjove shared with me.
These changes incorporate the latest ideas from the mailing list. There are two commits, the first commit keeps to what was on the mailing list and the second commit extends with the additional clawback operation for claimable balances that keep the operations used for clawing back explicit.
> CAP-0035: snapshot state in trustline and add claimable balances

- core/cap-0029.md
Remove an extra word that looks like a typo.
Just noticed while reading. It's not a big deal, just thought I'd fix it.
> CAP-0029: Remove typo

- core/cap-0035.md
Replace Bartek (@bartekn) with Eric (@ire-and-curses) in the Consulted role of the working group.
I added Bartek while Eric was unavailable, but now Eric is heavily involved and reviewing this from a Horizon and SDK perspective, and this change reflects reality.
> CAP-0035: Replace Bartek with Eric in the Consulted role of the working group

- core/cap-0035.md
Changes:
- Move extensions at top of new ledger entry structs to top rather than bottom.
- Define shared non-native asset code type to use in AllowTrustOp and new ops.
- Require that both are set auth revocable and auth clawback.
These change were decided in the [Open Protocol Meeting held on 2020-01-14].
Moving the extensions to the top of new ledger entry structs gives greater freedom to how extensions are applied in the future.
Defining a shared asset code definition simplifies the existing `AllowTrustOp` and the new `ClawbackOp`.
Requiring that `AUTH_REVOCABLE_FLAG` is set whenever `AUTH_CLAWBACK_ENABLED_FLAG` is set makes it harder for issuers to configure issuer accounts in such a way that they would be unable to clawback assets held by the selling liabilities of offers.
See the …
> CAP-0035: changes from the Open Protocol Meeting held on 2020-01-14

- core/cap-0035.md
Mention what happens to sponsored reserves when a claimable balance is clawed back.
@bartekn asked what happens on the mailing list, and whilst there is nothing unique being introduced regarding this feature we can add a statement making it clear that is the case.
> CAP-0035: mention sponsored reserve behavior

- core/cap-0035.md
This PR includes three changes -
1. Moved `AssetCode` below `AssetType` so we can compile.
2. XDR uses C-style enums, so the `CLAWBACK_ENABLED_FLAG` in trustline flags conflicts with the claimable balance flags. I changed the claimable balance flag to `CB_CLAWBACK_ENABLED_FLAG`.
3.  Removed `MASK_ACCOUNT_FLAGS_V16`. `MASK_ACCOUNT_FLAGS` is only used in the invariants, which is not part of the protocol. We can just change the value instead of introducing a new mask.
One other thing I noticed in the CAP is that the new `AUTH_CLAWBACK_ENABLED_FLAG`/`AUTH_REVOCABLE_FLAG` check in `SetOptionsOp` uses the `SET_OPTIONS_BAD_FLAGS` result code, which is currently used during validation. The new check will be done at apply time (since we need to load the account to learn which flags are currently …
> CAP-0035 - XDR fixes

- core/cap-0035.md
This commit adds some non-controversial changes to CAP-35:
* Renamed `CLAWBACK_CLAIMABLE_BALANCE_MALFORMED` to `CLAWBACK_CLAIMABLE_BALANCE_DOES_NOT_EXIST` to be consistent with `ClaimClaimableBalanceResultCode`.
* Changed `CLAWBACK_MALFORMED` description. `AssetCode` union cannot be malformed (invalid value will be catched by XDR decoder).
* Updated description of claimable balance clawback flag inheritance for clarity.
Some questions:
* I'm not sure if the proposal really solves the theft/fraud issues for liquid assets. Stolen funds can be easily exchanged to non-_clawbackable_ assets.
* Do we really need `amount` in `ClawbackOp`? Alternatively, we can clawback entire amount and send smaller amount back in the same transaction. It can simplify the implementation.
* Maybe we should …
> CAP-0035: remove _MALFORMED and add _DOES_NOT_EXIST

- .github/workflows/stale.yml
Close stale issues and pull requests automatically after 35 days with a 5 day warning.
@MonsieurNicolas pointed out that we've got a build up of stale issues and pull requests. This should help clean things up. It is non-destructive so issues and pull requests can be reopened by their authors if they get closed. We can improve a selection of labels that prevent auto-close.
> Close stale issues and pull requests automatically after 35 days

- core/cap-0035.md
`CLAWBACK_NOT_ISSUER` is unnecessary because the source account determines the issuer of the asset, similar to how `AllowTrustOp` works.
> CAP-0035 - remove unnecessary result code

- core/cap-0029.md
Define the working group for CAP-29.
It is currently undefined and implicit. It's worth making it explicit.
@tomerweller I made some assumptions about who should be consulted and included two people who work on Core and two people who work on the layers above Core. Let me know if you'd prefer different people named.
> CAP-0029: Define the working group

- ecosystem/sep-0006.md
- ecosystem/sep-0024.md
88312b04e1334147b8dab8763dce0ed58dcd3ce3 clarified the `asset_code` parameter to `/deposit` to be the code of the asset being deposited to the anchor's off-chain account. For example, if an anchor issues a `MyBTC` token, the client should still pass `BTC` as the `asset_code` parameter value.
This PR changes that to require clients to use the code of the anchored asset (`MyBTC` in the example). Here is why:
1. SEP-24 specifically states that the `asset_code` parameter should be the asset code of the anchored asset, not the off-chain asset. So this PR makes SEP-6 consistent with SEP-24.
2. Using potentially different asset codes for `/deposit` makes what the `/info` response should be unclear. In the `MyBTC` example, should `MyBTC` or `BTC` be listed in the `/info` response? This change …
> SEP-6 & SEP-24: make asset codes used consistent

- core/cap-0035.md
Added a new operation to set and clear only the specified trustline flags. This operation will allow an issuer to clear the `CLAWBACK_ENABLED_FLAG` from a trustline.
> CAP-0035 - Add new operation to modify trustline flags

- .github/workflows/stale.yml
Enable the stale GitHub Action that will close issues and PRs after 35 days of being stale with a 5 day warning.
See previous discussion here: #833.
> Close stale issues and pull requests automatically after 60 days

- core/cap-0035.md
Remove the word `effectively` that was weakening the statement about conceptually the asset in a clawback is returned to the asset issuers.
The CAP states that the asset is burned and that it is returned to the issuer, but it uses the word effectively that implies that isn't what happens. In some ways this isn't what happens because issuer accounts do not hold a balance of an asset they issue. Any amount of an asset they issue sent to them via a payment or a trade is burned. On Stellar the way that an asset is burned is to return it to the issuer. It's worth us discussing what happens with a clawback using the same terms and concepts so that there is clear that this burn is no different to any other burn.
In the real world clawback means taking back of something. The thing isn't vaporized …
> CAP-0035: Remove word weaking statement

- .github/workflows/stale.yml
Change the stale notification message to say that issues and pull requests will be closed after 30 days.
That's what the stale workflow will do, but the message says 5 days.
> Fix the stale notification message to say 30 days

- core/README.md
- core/cap-0036.md
Change the status of CAP-36 to rejected.
Support for the clawback of claimable balances has been adopted into CAP-35 and CAP-36 is no longer needed. There's been no formal call to reject it, but I authored it and think it should be withdrawn and status updated to reflect that we are not entertaining this idea.
> CAP-0036: Change status to Rejected

- core/cap-0035.md
1. Added a `SET_TRUST_LINE_FLAGS_INVALID_STATE` code that is returned if both `AUTHORIZED_FLAG` and `AUTHORIZED_TO_MAINTAIN_LIABILITIES_FLAG` are set during application.
2. Explained why `SetTrustLineFlagsOp` is useful.
> CAP-0035 - Add SetTrustLineFlags op result code and expand design rationale

- ecosystem/sep-0008.md
**What**
Add support for CORS header.
**Why**
CORS requests should be supported by the endpoint so that web apps on other domains can hit them cross-domain.
Closes #823 
cc @shredding @dmgmyza
> SEP-0008: support CORS header

- core/cap-0035.md
1. I removed `MASK_ACCOUNT_FLAGS_V16` from the original proposal, but I'm adding it back in since it'll be helpful to check for invalid flags based on protocol version in the invariants.
2. Updated usage of the outdated `CLAWBACK_ENABLED_FLAG` flag name.
> CAP-0035 - Add MASK_ACCOUNT_FLAGS_V16 and fix flag names

- ecosystem/sep-0012.md
Wallets need a way to check a user's KYC status even if the user isn't available to sign a SEP-10 request. This change adds a POST /customer endpoint that allows wallets to provide a callback URL. Anchors will POST whenever the status changes (in the same format as responses to GET /customer) until the user is accepted or rejected.
> SEP-12 callback endpoint

- core/cap-0035.md
This PR has a few changes -
1. Change `SetTrustLineFlagsOp` `AssetCode` parameter to `Asset` so we can extend use of this operation in the future.
2. Add additional validation conditions for the `Asset` parameter specified above.
3. Expand existing explanations.
> CAP-0035: Changes from the Open Protocol Meeting held on 2021-01-28

- ecosystem/sep-0008.md
Add and change statements that discuss the action_required response to state that the use of `action_fields` is optional for both the server to provide, and the client to use, and exists to allow the client to improve the UX by circumventing the need for the user to enter information.
Removed statements about the POST flow that were confusing and did not add a lot of value.
@howardtw pointed out some gaps in understanding when reviewing SEP-8 since #_ was merged.
This makes no functional changes to the specification, and only clarifies existing behavior.
> SEP-0008: Address ambiguities in the action_required use case

- core/cap-0035.md
Define what happens if an issuer creates a claimable balance.
@jonjove pointed out in https://github.com/stellar/stellar-core/pull/2893#discussion_r567064267 that the issuer can create a claimable balance but doesn't have a trustline to itself, and we need to define what the clawback enabled state of the claimable balance is in this case.
This was discussed on the mailing list starting [here](https://groups.google.com/g/stellar-dev/c/hPhkXhrl5-Y/m/Eg6VwKiCAQAJ) and consensus appears to be to set the claimable balances clawback enabled state based on the account flags in the case of the issuer account.
> CAP-0035: Define what happens if an issuer creates a claimable balance

- ecosystem/sep-0008.md
**What**
This PR adds the next step for the client to take after there is no more action to be done.
**Why**
It is unclear about what to do and what to expect when a user completes all the action required by the approval service.
> SEP-8: add next step for action_required status

- ecosystem/sep-0008.md
**What**
This PR adds an optional field `message` to the `follow_next_url` response.
**Why**
The client can choose to display the message to the user if the approval server requires further actions.
> SEP-8: add an optional message field along with next_url

- ecosystem/sep-0006.md
resolves stellar/stellar-protocol#775
Adds the `on_change_callback` request parameter to `/deposit` and `/withdraw` requests to match the functionality added SEP-24 ([PR](https://github.com/stellar/stellar-protocol/pull/739)).
The `kyc_verified` attribute is not relevant in SEP-6 because requests to `/deposit` and `/withdraw` return 400 until KYC has been verified. Only after KYC is verified do `/deposit` and `/withdraw` requests succeed and records are created and retrievable from `GET /transaction(s)`.
One thing that is not clear is if the anchor should return 400 if `on_change_callback` is not supported. I think it should, but its more likely that anchors would simply ignore the parameter (especially since it's a new addition and they don't know to check for it)
> SEP-6: added on_change_callback parameter to /withdraw and /deposit requests

- ecosystem/sep-0024.md
resolves #862
Adds a new section outlines how the interactive flow popups should be closed. Previously it was implied that the wallet would close interactive flows, but this is unnecessary and having the anchor or user close the popup reduced complexity and provides a better UX.
Once merged, we'll announce the change to the ecosystem and set a date on which we expect anchors to update by.
@pitsevich
@dmgmyza
> SEP-24: anchors or users should close interactive popups

- ecosystem/sep-0010.md
Make clear in the token endpoint flow that there are multiple operations in the challenge transaction and that the verification steps are focused on the first operation.
In SEP-10 v3.1 we added a new operation that is included but the token endpoint flow was not updated to reflect that this was the case. The token endpoint flow talks about the transaction having a single operation and verifying that operation which is confusing.
This change makes no functional changes and updates the token endpoint section to align with the rest of the document.
> SEP-0010: Fix inconsistencies in flow defined by the token endpoint (v3.1.1)

- ecosystem/sep-0006.md
Originally discussed in stellar/stellar-protocol#808 
Adds two optional parameters to both `/deposit` and `/withdraw`: `amount` and `country_code`. These fields may be necessary for the anchor to know what SEP-9 `fields` to return in the response.
One change I didn't make, is adding a `sep12_type` parameter that is associated with the `fields` list returned. We could add this attribute to enable the client to make `GET /customer?type=` requests. However, specifying both `fields` and `sep12_type` is redundant, so `fields` may need to be deprecated if we wanted to add `sep12_type`.
> SEP-6: Added optional 'amount' & 'country_code' parameters

- ecosystem/sep-0006.md
resolves #796 
Adds support to SEP-6 for using claimable balance operations instead of waiting for a trustline to be established. The changes mirror [those made to SEP-24](#757) as closely as possible.
> SEP-6: update SEP-6 for claimable balances

- ecosystem/sep-0024.md
Deprecates the use of `postMessage` callbacks.
Question: Do we want to deprecate the `callback` parameter altogether? `callback` is used for when the interactive flow has completed. But now that ~it is the anchor's responsibility to close the popup~ the user must close the popup, I can't think of a reason why `callback` is valuable. `on_change_callback` can be used for all status changes, so the wallet could get an update when the transaction moves to `pending_user_transfer_start`.
> SEP-24: deprecated postMessage callbacks

- ecosystem/README.md
- ecosystem/sep-0026.md
resolves #793
SEP-6 is already used in the wild and it would be a burden on client applications to support SEP-26 as well. SEP-6 is still in _Active_ status and can be improved upon if desired.
> SEP-26: reject in favor of SEP-6

- ecosystem/sep-0010.md
This change does not change any functionality related to SEP-10. Rather, it better defines the participants involved in the process and updating the document to always reference those participant definitions. This will help avoid confusion when referencing the participants, instead of using general terms like `client` and `server`.
If merged, I'll update #760 to use the term **Client Server**
> SEP-10: Clarifying Participants

- core/cap-0035.md
This PR changes the `SetTrustLineFlagsOp` `setFlags`/`clearFlags` parameter to no longer be optional. They were made optional initially because that is how `setOptionsOp` worked, and we were mimicking the structure of that operation. After some discussion, we came to the conclusion that it would be simpler if we just dropped the pointer. Tagging @2opremio as this will affect Horizon.
I also added a comment about how `SetTrustLineFlagsOp` uses the updated logic in CAP-0029.
> CAP-0035 - Changes after code review

- ecosystem/sep-0008.md
Fix inconsistency by updating snippet JSON field from `message` to `error`.
While the table recommended using `error` the JSON snippet had the `message` field instead. 
Also, it was already called `error` in previous protocol versions.
> SEP-0008: Fix inconsistency by updating snippet JSON field from "message" to "error"

- ecosystem/sep-0006.md
resolves stellar/stellar-protocol#861
Adds optional `id` attributes to the `/deposit` & `/withdraw` success responses. This removes need for clients to infer which `/transactions` record is associated with a particular request.
> SEP-6: added 'id' response attributes for /deposit & /withdraw

- .github/workflows/stale.yml
Change the message that is posted as a comment when issues are identified as stale to remove the statement about leaving a comment.
I've noticed a pattern that when we want to keep issues alive we post brief and mostly meaningless messages to issues like "Not stale". We should recommend folks just remove the stale label so we don't add unnecessary comments to peoples inboxes and to the issue history.
> Change the stale issue comment message.

- ecosystem/sep-0023.md
Improve the proposed Horizon API changes to rename the suffix `_id` to `_muxed_id`.
OrbitLens was talking to me about how the _id_id example highlights how using an _id suffix is not very pretty or specific to this new data we're displaying. _muxed_id would more clearly identify the field apart from others. 
It's possible there are better improvements, but this at least better than what's here.
> SEP-23: Improve proposed Horizon API changes

- ecosystem/sep-0008.md
For a brief moment in time we were using company names as authors. As per current standards this update replaces Lightyear.io with the original author - me :)
> SEP-0008: Update author list to current standards

- ecosystem/sep-0008.md
Add discussion about when to use a revised status and when not to. Specifically distinguish that a revised transaction should never change the intent or semantics of the operations the user provided.
There was some conversation about this recently within SDF and we realize it is not clear in SEP-8 when to use reject or when to use revised. In general revised shouldn't alter the intent. If the user wants to perform an operation and it can succeed if the server adds operations, that's the perfect use case for revised. If the user wants to perform an operation that is not compliant no matter what operations can be added, it should just reject the transaction rather than try and modify the transaction.
> SEP-0008: Add discussion about when to use a revised status and when not to

- ecosystem/sep-0024.md
Originally discussed in #875 
The SEP was recently updated to re-enforce the expectation that transaction begin in the `incomplete` status. However in that change we also incorrectly made the assumption that `pending_user_transfer_start` would always be the next status.
In fact, there are cases where other status are used directly after `incomplete`, such as if the anchor needs additional time to verify KYC information provided before accepting funds.
> SEP-24: clarify 'incomplete' status transition

- ecosystem/README.md
- ecosystem/sep-0033.md
Make SEP-33 active and set the version to v1.
The SEP is being used in several products in the ecosystem, namely stellar.expert, the Lobstr.co wallet, and I think some other places. There are several implementations, and the number of implementations is growing (#890). These are all indicators that this proposal/protocol is more than just a draft at this point. It's actively in use and the status should reflect that.
@pitsevich You're the author of this proposal. Do you agree?
> SEP-0033: Set version and make active

- ecosystem/sep-0001.md
resolves #903 
Adds an explicit support email attribute to the organization fields for SEP-1, and redefines the `ORG_OFFICIAL_EMAIL` to be for business inquiries.
> SEP-1: Add ORG_SUPPORT_EMAIL, updated definition of ORG_OFFICIAL_EMAIL

- ecosystem/sep-0031.md
While working on a change to SEP-31, I noticed how many grammar & punctuation mistakes there were, as well as how information could be better presented. This is a low-priority PR but would be nice to get merged.
> SEP-31: improve grammar, phrasing, and structure

- ecosystem/sep-0038.md
In the original PR for creating this protocol, we opted to not add a `GET /quote/:id` endpoint with the rationale that the client could store previously provided quotes in their own persistent storage.
However, this assumption places an unnecessary requirement on client-side implementations. It also means that a user would only be able to fetch quote details from the application used to originally request the quote.
> SEP-38: add a GET /quote endpoint

- ecosystem/sep-0001.md
Adds a stellar.toml attribute for SEP-38. Another possible name is `ANCHOR_RFQ_SERVER`. `ANCHOR` is an important word to include because it differentiates the protocol from a potential future SEP that supports exchange of on-chain assets.
> SEP-1: add ANCHOR_QUOTE_SERVER to specification

- ecosystem/sep-0038.md
I thought it would be helpful to include examples of the requests and responses for each endpoint, similar to what we have in SEP-31. 
In the process of writing these, I realized that the formula described in the `buy_amount` attribute description was incorrect based on the definition of `price` we've defined. I updated the patch version, but I could see an argument for a minor version increment.
> SEP-38: Add request examples

- core/cap-0038.md
1. Removes auth check from `LiquidityPoolWithdrawOp`.
2. Use `TrustLineAsset` in `SetTrustlineFlagsOp.
3. Add some minor details.
> CAP-0038 - Auth related updates

- cap-template.md
Add examples of how to generate and apply diffs in XDR files in CAPs.
Generating a diff is relatively self-explanatory and simple, but it is worth calling out to people we expect them to just use a git diff and not to generate an entire patch containing commits.
Applying a diff is relatively painful, especially for diffs that have been pasted into markdown files. Diffs in markdown files will almost always have whitespace inconsistencies that will cause the naked git apply command to error. It is capable of overlooking or fixing most whitespace errors and for folks who are unfamiliar with git apply the reject command is more useful because if there are conflicts it will leave the local space in a state that can be manually repaired.
This might be too prescriptive for folks who have their …
> CAP: Add examples of how to generate and apply diffs of xdr files

- core/cap-0021.md
Add another type of two-way payment channel design to the rationale that uses two escrow accounts and does not use claimable balances.
I've been expanding on the definition of the existing two-way payment channel in CAP-21, writing out all of the different steps, how fees would work, etc. The full write up I've done is here:
https://github.com/stellar/experimental-payment-channels/pull/3
After doing the write up I'm reasonably certain that even though on the surface it appears that a single escrow account is required, two 2-of-2 multisig accounts would likely be necessary in a real product. I think it will be required because claimable balances require a sponsor, and the sponsor is bound to them and can't be merged until they are claimed. To keep claimable balance sponsorship from binding …
> CAP-21: Add another type of two-way payment channel that uses two escrow accounts

- ecosystem/sep-0012.md
When I read the description of the payload POST callback_url, it wasn't clear to me whether it should be the same as the GET /customer request or response although the GET request body should not have any meaning.
> SEP-0012: make payload of POST callback_url clear

- ecosystem/sep-0009.md
Update SEP-9 `birth_place` field type from "date" to "string".
The field description says _"Place of birth (city, state, country; as on passport)"_ so I'm assuming its type should actually be "string".
> SEP-0009: update "birth_place" field type from date to string

- ecosystem/sep-0006.md
**Context**
As part of an ongoing effort to improve the usability of our protocols, in Q1 of 2021 SDF held an internal review of several SEP titles with the goal of choosing usable, descriptive names. 
Our protocols have developed over many years and as they and the ecosystem have grown, the names that they were originally given have sometimes become less meaningful. We’ve found ourselves often referring to a protocol by its number instead of its title, which can be confusing for new members as it abstracts the meaning of the SEP in discussion. While we’ll continue to use the SEP-# namespace in technical discussions and in order to maintain searchability, this step towards plain language names will hopefully encourage their usage in addition to the numeric shorthand.
**Before: …
> Updating SEP-6 title for clarity and usability

- core/README.md
- core/core-0039.md
Add a proposal to snapshot and limit the revocable state of a trustline to the state of the issuer account when the trustline is created and the issuer had the not revocable flag set, similar to clawback behavior.
See the CAP.
> CAP-39: Add proposal to snapshot and limit revocation

- ecosystem/sep-0008.md
Make the action_required text clearer upfront that this state is intended to require user interaction with a browser, however that there are capabilities to allow a client to skip it if it has the necessary information.
It has been surprising to a few folks that user interaction with a browser is required because one of the two options for replying is a POST request.
> SEP-8: Be clear about the action_required step being interactive

- core/cap-0038.md
1. Use a revocation strategy that follows how offers work today by redeeming all relevant pool shares when an asset trust line has its authorization revoked.
2. Make the trustor sponsor the claimable balances on revoke instead of the issuer.
3. Add a section for the previously proposed revoke strategy.
> CAP-0038 - update auth revoke logic

- ecosystem/sep-0012.md
Recommends clients always pass the customer `type` in `GET` & `PUT` requests.
I discovered that our `testanchor.stellar.org` SEP-12 implementation was returning `NEEDS_INFO` status values for customers who had passed all required fields for a SEP-6 deposit and received a customer `id`.
Upon further inspection I realized that this was because our `sep6-withdraw` customer `type` requires additional fields that the `sep6-deposit` `type` value does not, and the server was being conservative by assuming the request was for the `type` that required the most information.
Therefore, in order to ensure the correct `status` is returned for a customer in `GET /customer`, `type` should always be passed unless no types are specified in the SEP-31 or SEP-6 implementation.
> SEP-12: clarify the need for 'type' parameters in GET and PUT requests

- .github/workflows/mddiffcheck.yml
- core/cap-0021.md
- core/cap-0035.md
- core/cap-0036.md
- core/cap-0037.md
- core/cap-0038.md
- core/cap-0039.md
Add a GitHub Action that check the diffs in CAPs are valid.
On a few occasions diffs have been committed that are corrupt. This is usually discovered by someone consuming the diff, and not by the person publishing the diff. This consumes that other persons time, as they need to debug the diff. Diffs are fiddly and it's easy for copy paste errors to occur, or stray characters, or missing new lines at the end to result in a corrupt diff. Instructions introduced in 9b0d752c7ac4d42c9735789cb190479ee8744a33 should help us generate good diffs, but this check will catch the corrupt diffs when the author is submitting them, before someone else is consuming them.
Some of the existing CAPs were easy to update to pass the check. Others not, some just don't seem to apply cleanly to any version as far …
> meta: add cap diff check

- ecosystem/sep-0031.md
Disambiguate parts of the SEP and add further recommendation about refunded transactions.
When reading the SEP, some details and interactions between Sending and Receiving Anchors were not very clear.
> SEP-31: include some details about the Sending and Receiving Anchors to make the SEP clearer

- core/cap-0023.md
The implementation (unfortunately) ended up using the `AccountID` and converting it into the `MuxedAccount`. This PR updates the XDR to make it clear that the transaction source `MuxedAccount` is not used in `OperationID`.
> Change operationID to use an AccountID instead of MuxedAccount

- ecosystem/sep-0009.md
resolves stellar/stellar-protocol#915 
Uses `other` instead of the suggested `undefined` since `undefined` could be interpreted to mean `null` or simply omitted.
@ymatienzo
> SEP-9: add 'sex' field

- core/cap-0038.md
The current proposal stores `liquidityPoolID` under a union in `LedgerPoolEntry`, while the `LIQUIDITY_POOL` `LedgerKey` does not use a union for its `liquidityPoolID`. This doesn't make much sense because every pool type will need a `liquidityPoolID`, so this PR pulls the `liquidityPoolID` from the union in LedgerPoolEntry.
> CAP-0038 - Remove liquidityPoolID from union in LedgerPoolEntry

- ecosystem/sep-0012.md
I made a mistake when making the changes for #812. I suspect I thought I was altering a `GET /customer` or `PUT /customer/verification` response, but `id` is the only property allowed for `PUT /customer` responses.
> SEP-12: fix PUT /customer response example

- ecosystem/sep-0010.md
Add a requirement to SEP-10 that the server should return only one JWT token for a given challenge, without prescribing exactly how that is achieved.
It is a best practice to not allow multiple authentication tokens be collected through a handshake process. While this SEP does not attempt to mention all best practices relating to JWTs and other things, I think it could be worth mentioning this one.
Realistically there is probably little someone could do with an average SEP-10 server, but it may be confusing if there are multiple JWTs that were all related to one challenge.
The change doesn't prescribe how to implement this because I don't think it is particularly important, at least not yet to force a particular implementation on an implementation. A server may implement this by making …
> SEP-10: Add requirement that server should return only one JWT token for a challenge

- ecosystem/sep-0038.md
Make a few updates to SEP-38 for improved clarity and usability:
* Fix example response from the `GET /quote` request.
* Add parameters `sell_asset` and `buy_asset` to the responses from `GET /quote/{id}` because without these fields the request won't provide much valuable information
* Update the response from `POST /quote` to be consistent with the changes added to `GET /quote`
* Make it clear that fees are included in the prices from `GET /prices` and `GET /price`
* Add a statement about the indicative price being an estimate, so the actual price will be calculated at conversion time.
* Fix inconsistency between `delivery_methods` field description and examples.
> SEP-38: fixes and improvements

- ecosystem/sep-0012.md
resolves stellar/stellar-protocol#981
Changes:
- Clarifies `fields` to be an object containing SEP-9 fields that have not yet been collected by the anchor
- Adds `provided_fields` for SEP-9 fields that have been collected
- Moves field `status` and `error` properties from `fields` to `provided_fields`
- Removes `NOT_PROVIDED` as a value for field `status`
Open questions:
- Do we want to add a new `VERIFICATION_REQUIRED` customer-level status to better indicate what the anchor is waiting on?
`NEEDS_INFO` is primarily for indicating that the customer must provide more information detailed in `fields`. However, anchors that require verification of provided fields are instructed to use `NEEDS_INFO` as well. If all fields have been provided it may be confusing for the client to still see …
> SEP-12: Clarify existing vs. provided fields

- core/cap-0038.md
Improves the consistency of validation results for `RevokeSponsorshipOp`.
> CAP-38: Use REVOKE_SPONSORSHIP_MALFORMED in more cases

- ecosystem/README.md
- ecosystem/sep-0023.md
Update the status of SEP-23 to Active, set version to v1.0.0.
The SEP is implemented in Horizon, the Go SDK, the JS SDK, stc, and more. At this point the inertia that would be required to change SEP-23 is significantly high because changing it would require breaking changes to all these things. Even though in some of these things the functionality SEP-23 defines is specified as opt-in the implementation carries weight that'll be difficult to coordinate in changing. Therefore I think this SEP should be considered in active status, and not draft. It has moved past being a draft because we would not make arbitrary changes to it at this point.
cc @stanford-scs @tomerweller @ire-and-curses @shanzzam @2opremio
> SEP-23: Update status to Active

- ecosystem/README.md
Remove Tom Q from the SEP team, and add Leigh and Jake.
I'm not really sure the SEP team definition is as distinct or important as the CAP team is, but it looks out of date, and myself and Jake make decisions about state transitions of SEPs. It's possible we should remove this list of people all together, but that seems like a larger conversation to have and once updated the list does seem somewhat accurate indication of the people who will typically approve SEPs.
> SEP: Update Team

- ecosystem/README.md
Add instructions about how to set the version number in SEPs.
We have no instructions for how to use versions, and that leads to some unfortunate situations during the draft state of a SEP. It's happened where we start a draft of a new SEP, start with v1, and then a little while later while it is still in draft we want to make a breaking change and need to change to v2. Drafts are intended to be a work-in-progress where unrestrained iteration is occurring, anything can change, and in semantic versioning that's what the v0 major version is intended for.
> SEP: Add details about SEP versioning

- core/cap-0021.md
Update the discussion URL to the new mailing list thread.
The discussion URL is pointing to the old thread. The new mailing list thread is where all discussion is happening now.
> CAP-21: Update discussion URL

- core/README.md
- core/cap-0040.md
Add a proposal to add an ed25519 signed hash signer for use alongside the precondition primitives, specifically the `extraSigners` precondition, that are proposed in CAP-21.
See within the document.
Close stellar/experimental-payment-channels#165
> CAP-40: Add proposal to add a ed25519 signed payload signer

- core/cap-0040.md
Add discussion URL to CAP-40.
There is now a mailing list discussion thread for the CAP.
> CAP-40: Add discussion URL

- core/cap-0040.md
Wrap the ed25519 signed payload signer key fields in a struct in the union.
There can only be a single value in each case of the union.
> CAP-40: Fix ed25519 signed payload signer key xdr

- ecosystem/sep-0038.md
1. Replace `delivery_methods` with `buy_delivery_methods` and `sell_delivery_methods`.
2. Update request parameters of `GET /price`, `GET /prices` and `POST /quote` endpoints so the fee can be accurately calculated with the new parameters provided:
* `sell_delivery_method`
* `buy_delivery_method`
* `country_code`
2. Add `country_codes` parameter to the `GET /info` endpoint
4. Fix request example for `GET /quote`.
> SEP-38: distinguish sell/buy delivery methods for fee calculation

- core/cap-0040.md
Update the max size of the transaction batch to 3.
CAP-21 has been updated to support a max length of 2 in extraSigners.
> CAP-40: Update max size of transaction batch to 3

- core/cap-0040.md
Change the signature hint of the signed payload to be the same hint as the ed25519 public key within the signed payload.
For two reasons:
1. In all existing signers the hint is derivable from both the public information and the secret information.
For example:
- An ed25519 signer's hint can be derived from the public key, or from the secret key by first deriving the public key from the secret key, then the hint from the public key.
- A hash(x) signer's hint can be derived from the public hash(x), or from the secret x by first hashing x, then deriving the hint from the hash.
The way that the signature hint is defined as being an xor of both the ed25519 public key and the payload means that code that intends to calculate the hint needs to know not only the secret component, the ed25519 …
> CAP-40: Change hint to the hint of the ed25519

- core/cap-0038.md
The values are also propagated to Stellar-Core code: https://github.com/stellar/stellar-core/compare/v17.2.0...v17.3.0rc1#diff-11f6a6577ee4d25e4eb1b1834bd71486cc73c26ad4eda68345286a27f5d74307R999-R1000
> ChangeTrustResultCode negative values in CAP-38

- core/cap-0040.md
Make the hint of the signer the xor of the last 4 bytes of the public key and the last 4 bytes of the payload.
@stanford-scs pointed out that in the use cases we plan to use the new signer there would almost always be two sigantures using the public key on the transaction, one a regular signature, and one a payload signature. It isn't great if applications verification signatures have to verify 2x the signatures for every one of these transactions simply because the payload signature uses the same hint.
It is inconvenient for applications to make the hint not the same as the public key's hint because it will not be as simple as copying the decorated signature from one transaction with the payload to the transaction the payload signature disclosed. But that inconvenience is not …
> CAP-40: Make hint the xor of public key and payload

- ecosystem/sep-0010.md
for the client verification of the challenge: adds that the source account of the manage data operation must be the client domain account in case that the manage data operation key is "client_domain" and not the server account
> SEP-10: improve discovery flow

- core/cap-0040.md
Define for the signature hint of the signer introduced by CAP-40's what happens if the payload is less than 4 bytes, stating that zero bytes are appended to make it 4 bytes just for the calculation of the hint.
This case is not particularly likely given that the use cases for payloads is to use the full 32 bytes, but I think the definition of the hint should be complete and cover all cases none-the-less.
For https://github.com/stellar/experimental-payment-channels/issues/196
> CAP-40: Address short payload cases

- core/cap-0040.md
Expand on the use cases and impact of using CAP-40 on the number of messages.
I realized that this is not particularly clear and the design rationale did not discuss it in as much detail as we have discussed in some in person conversations. I think this fleshes it out a bit. This doesn't change the proposal in any way.
> CAP-40: Expand on use cases in design rationale

- core/cap-0040.md
Correct max length of zero byte padding for hint calculation.
@ire-and-curses pointed out that nothing in the specification sets a minimum length for payload, and since it can be zero, the hint may need to be padded to four bytes which is beyond the specified 3 bytes.
https://groups.google.com/g/stellar-dev/c/Wp7gNaJvt40/m/CcvxiOPHBAAJ
> CAP-40: Correct max length of zero byte padding for hint calc

- core/cap-0038.md
This PR has two changes-
1. Clears up the possible scenarios when the authorization for an asset in a pool is revoked.
2. Specifies what happens on a revoke where there is no asset balance to withdraw. (@tamirms this might interest you)
> Clarify and handle all pool revoke scenarios

- core/cap-0021.md
Add some notes about resource utilization.
I noticed that one side-effect benefit of CAP-21's `extraSigners` is we make the use cases of the existing HASH_X signer more efficient since there is now no, or little, reason to store them on ledger as an account signer. I feel like it is worth calling that out, that this proposal may in some ways improve utilization, albeit small.
While adding a brief blurb about that, it felt natural to add some other comments about utilization that were missing.
> CAP-21: Add some notes about resource utilization

- ecosystem/sep-0012.md
I noticed that our markdown referenced a heading title that didn't exist, so I updated the heading appropriately.
> SEP-12: rename 'Field Statuses' heading to 'Provided Field Statuses'

- ecosystem/sep-0006.md
- ecosystem/sep-0024.md
- ecosystem/sep-0031.md
resolves #1039 
With the exception of adding a required `account` field to SEP-6's `deposit-exchange` endpoint, the changes here are largely patch-level changes that clarify the ability to send and receive funds to and from accounts that were not used in SEP-10 authentication.
Its possible that anchors assume deposits are always made to the account authenticated via SEP-10. Hopefully these anchors reject requests that specify `account` parameters that differ from the authenticated account. If they do not, anchors would mistakenly send funds to the account authenticated via SEP-10 instead of account provided in the deposit request. However, this should not be a major issue since the client has access to the authenticated account and can send the funds to the correct account.
> SEP-6, SEP-31: add explicit support for source and destination accounts different than authenticated accounts

- ecosystem/sep-0006.md
- ecosystem/sep-0024.md
resolves #1030
Adds a `feature_flags` object to `GET /info`'s response body containing boolean values indicating whether or not specific features are support by the anchor. Currently the only two values and defaults are:
- `account_creation`: `true`
- `claimable_balances`: `false`
As ecosystem adoption for claimable balances increases, the feature flag's default may be updated to `true`.
This is helpful for clients who would adjust their behavior or UX based on the anchor's supported features. For example, a wallet could either require that a user create an account prior to requesting a deposit if the account didn't exist and `account_creation` was `false`, or require the user to create a trustline prior to requesting a deposit if `claimable_balances` was `false`.
> SEP-6 & 24: Add `features` object to GET /info

- core/cap-0038.md
`CLAIMABLE_BALANCE_ID_TYPE_FROM_POOL_REVOKE` was removed in one of previous commits but the new type is still referenced.
See: https://github.com/stellar/stellar-core/pull/3162#discussion_r702150851
> Remove a new ClaimableBalanceIDType mention in CAP-38

- ecosystem/sep-0031.md
1. Changed "Receiver Anchor" to "Receiving Anchor" to make the document consistent.
2. The word "Receiving Anchor requests" sounds like the receiving anchor is polling information from the sending anchor. But it should be the sending anchor "patching" to receiving anchor. Change the wording to avoid the confusion.
> Modify the wording of PATCH /transactions/:id description

- ecosystem/sep-0008.md
Change the heading of the flow section to transaction flow instead of approval flow.
The section details how a client transacts and what they need to do, part of which is approval. I think it makes it easier to understand that if we refer to this as the transaction flow. It is not only about approval.
> SEP-8: Change heading

- ecosystem/sep-0008.md
- ecosystem/sep-0031.md
Distinguish between assets that simply require authorization from assets that are regulated assets.
An asset can require authorization without being a regulated asset or having an approval server. I think it is helpful to set this distinction and be clear that an asset requiring authorization without the issuer having an approval server is not a "SEP-8 Regulated Asset", although it may be a "regulated asset" by some other definition.
> SEP-8: Distinguish requires auth vs regulated asset

- core/cap-0021.md
Add to the security section about transaction validity an example, and a statement for protocols to test again.
The security section highlights that transaction validity vs failure during execution is something to be aware of but without further discussion it may not be grasped by the reader.
Thinking through the example helped me understand the problem better and would probably help others.
Making a statement like "if you do X, don't do Y" is also helpful at understanding what the distinction is between a transaction that is safe or unsafe in this context.
> CAP-21: Expand on the transaction validity/execution aspected in the security section

- ecosystem/sep-0038.md
We forgot to document the status codes that should be returned in success responses for SEP-38 requests.
> SEP-38: add status codes

- ecosystem/sep-0024.md
Adds support for exchanging non-equivalent assets (i.e. using quotes) in SEP-24. Note SEP-38 is not required, unlike in SEP-6 and SEP-31, because all quote-related info can be communicated via the interactive flow.
Note the change made to the `GET /fee` endpoint description. This is a temporary change while the decision around deprecating the `GET /fee` endpoint altogether is finalized (see #1061).
> SEP-24: Add support for transacting non-equivalent assets

- ecosystem/sep-0006.md
resolves #1061
Adds a disclaimer to the `GET /fee` endpoint for a lack of multi-asset transaction support. The fee endpoint will only support reporting fees in terms of Stellar assets for amounts of the same Stellar asset.
Also corrects the description of `fee_fixed` and `fee_percent` for deposit assets. Fees cannot be expressed in terms of the off-chain asset in these cases because the fee values would vary per off-chain asset.
> SEP-6: clarify GET /fee endpoint usage for Stellar assets

- core/cap-0021.md
Add deterministic account creation as a use case in the design rational section of CAP-21.
See the change for why this is useful.
> CAP-21: Add deterministic account creation use case to design rationale

- ecosystem/sep-0024.md
resolves #864 
Removes the no-additional-info-needed response from the withdrawal endpoint, making it consistent with the responses offered for the deposit endpoint.
I can see a future where wallets concerned about UX want the ability to skip the interactive flow entirely, but we can add responses back for both endpoints when that use case arises.
> SEP-24: remove unused withdrawal response

- ecosystem/sep-0038.md
The `buy_delivery_method` and `sell_delivery_method` parameters on the `GET /price`, `GET /prices`, and `POST /quote` endpoints are used to provide the anchor with additional information that can be used to adjust the price and expiration provided in the response.
However, client have reasons to make requests to the `GET /price(s)` endpoints other than actually exchanging the assets, namely:
- Displaying the available pairs
- Displaying an estimated exchange rates prior to the user initiating a transaction
For the above use cases, especially the first, its not strictly necessary to specify how the user will deliver or pick up the off-chain asset to the anchor. The anchor can decide to show its best rates when not specified.
For `POST /quote`, the delivery method parameters are certainly …
> SEP-38: relax the requirements for specifying delivery methods

- ecosystem/sep-0024.md
Un-deprecates the use of `postMessage` callbacks and adds a section outlining recommendations for it's usage.
I also added a section detailing how `postMessage` callbacks can be used to signal to the wallet to close the anchor's window triggered by user action. This the pattern we're seeing develop in the ecosystem.
cc @pitsevich
> SEP-24: Un-deprecate `postMessage` callbacks and add security section

- ecosystem/sep-0010.md
This PR updates the "Verifying Client Application Identity" copy to read "Verifying the Client Domain" instead (like it's appearing in all the other places in the doc) and fix the hyperlink.
> SEP-10: Fix "Verifying the Client Domain" hyperlink

- sep-template.md
Add updated and version pragma to SEP template.
The fields are frequently used in many SEPs. The ecosystem folder's README even details instructions for how the version field should be used. It looks like it was never added to the template.
The version in the template is set to 0.1.0 because for a new draft SEP that's the typical version we'll use, keeping the major number 0.
> SEP: Add updated and version pragma to sep template

- ecosystem/sep-0009.md
Add organization registration date to SEP-9.
It's been reported in #1074 that the registration date of a business is a field that is commonly asked for during onboarding. This field is currently missing in the organization KYC fields and it would be useful if we included it given it is common.
Close #1074
cc @ymatienzo
> SEP-9: Add organization registration date

- sep-template.md
Add a very lightweight changelog section to the SEP template.
This idea was suggested by @marcelosalloum in https://github.com/stellar/stellar-protocol/issues/1046#issuecomment-995861028.
SEP documents evolve over time but there is no location where a reader can quickly read in prose a description of what has changed from one version to the next. While the Git history and PR descriptions for changes made to the SEP provide insights it requires a lot of effort for a reader to sift through all that information to find what the final incremental changes are that have been made.
Requiring a changelog entry will also help us evaluate the necessity and clarity of a change since the changelog is persisted forever we must choose wisely the changes we make.
The changelog @marcelosalloum had …
> SEP: Add changelog section to SEP template

- ecosystem/README.md
Add notes about when versions should be updated and exception cases.
We've had the rule for a while versions always get updated, and it is working well. There are some exception cases where it doesn't make sense to do it since these exception cases have nothing to do with the content of the SEP.
> SEP: Add clarification to when versions should be updated

- core/cap-0040.md
Expand payload max to 64 bytes.
See updated proposal. This was suggested by @stanford-scs.
> CAP-40: Expand payload max to 64 bytes

- core/cap-0040.md
Removed the discussion about how a transaction hash is produced from the semantics, and moved it to the design rationale.
Feedback from @Shaptic highlighted that the section in the semantics section about how the transaction hash was constructed was confusing as it was presented like a new process that takes place, when in fact this is just the regular process all transaction hashes go through.
I moved it to the design rationale because that content relates more to how the changes will be used, and it is not really semantics of the change itself.
> CAP-40: Make some text clearer

- ecosystem/sep-0006.md
- ecosystem/sep-0024.md
- ecosystem/sep-0031.md
resolves #1122 
Deprecates the `refunded` attribute included in objects returned from `GET /transaction(s)` endpoints for SEP-6, 24, & 31 in favor of adding a `refund` object.
This refund object contains information about the type of refund, total amount refunded, and the individual payments made back to the sender / user. 
Note that SEP-31 refunds are assumed to be made via Stellar (since funds are always delivered to receiving anchors via Stellar).
> Transfer SEPS: deprecate `refunded` boolean, add `refunds` object to transaction records

- core/cap-0045.md
The argument as written does not fully justify the protocol's choice of liquidity pool trading rule (there are quite a few formulae that would satisfy the earlier argument).  Namely, it shows that using the specified formula, the liquidity pool trades in the expected directions, but does not justify trade amounts.
I also switched notation of the form a / b / c to a / (b * c), which is (in my view) easier to read.
> Correction to the argument supporting the liquidity pool's trading rule

- ecosystem/sep-0038.md
Make SEP-10 token optional for the endpoints:
* `GET /info`
* `GET /price`
* `GET /prices`
Client applications may want to show rates from multiple liquidity providers to a user, or simply display the exchange rates of an anchor's pairs before the user has indicated they want to start a transaction.
Closes #1086.
> SEP-38: make SEP-10 token optional for some endpoints

- ecosystem/sep-0031.md
Adds a "Diagrams" section to SEP-31 and starts with a happy-path sequence diagram.
We've discussed whether or not to include diagrams in our SEPs several times in the past and have historically decided not to do so due to the additional burden of maintaining another document. However, now that Github has added support for mermaid syntax, we can keep the SEP as the single source of truth and edit diagrams directly as markdown.
> SEP-31: Add mermaid sequence diagram

- ecosystem/sep-0038.md
Add note to SEP-38 about the `expires_at` and `expire_after` fields and their relationship, and how `expires_at` can occur after `expire_after`.
This is pre-existing behavior and intent, but on reading the table it wasn't completely obvious to me that was the intent. Adding this additional note might help prevent someone else from missing this.
> SEP-38: Add note about expires_at and expires_after and their relationship

- ecosystem/sep-0031.md
In the following scenario, the receiving client may receive on-stellar asset. 
Sending client --off-stellar --> Sending Anchor
Sending Anchor --on-stellar --> Receiving Anchor
Receiving Anchor--on-stellar --> Receiving Client
In this use case, the sending customer does not have a Stellar account and Receiving Client has a Stellar account. We should add on-stellar asset to the receiving client.
> Add on-stellar asset for receiving client.

- core/cap-0021.md
- core/cap-0040.md
This PR makes three changes - 
1. Specifies a failure case when the CAP-0040 signer is used prior to the protocol upgrade.
2. Removes the `TimePoint` change because this is what was agreed upon in the protocol meeting (link to the [Discord](https://discord.com/channels/897514728459468821/946566916783357972/953389257739878421) discussion with more context).
3. Update the `maxLedger == 0` scenario to disable the `maxLedger` check (link to [Discord](https://discord.com/channels/897514728459468821/946566916783357972/951637761767657492) discussion with more context).
> CAP-0021 and CAP-0040 updates

- ecosystem/sep-0006.md
Adds a sequence diagram to the SEP-6 protocol documenting a withdrawal flow, specifically for using SEP-38 firm quotes.
This flow is very similar to the SEP-31 diagram added in #1145.
> SEP-6: add firm quote withdrawal mermaid diagram

- core/cap-0021.md
Add a note in security concerns of CAP-21 about the presence of free-options in multi-party protocols.
@jonjove highlighted the presence of a free-option in the protocols defined in the design rationale. This is not unique to these protocols, not unique to CAP-21, and not unique to Stellar, and plagues many multi-party protocols, especially payment channel protocols.
I was on the fence if we should even mention it, since it is not really a security concern of CAP-21 itself, and more an educational warning of something to keep in mind when building the types of protocols that CAP-21 makes more possible. To be clear too this problem can arise with protocols that do not use any of CAP-21's features. However, the problem's relevance to the topic and design rationale feels too intense to …
> CAP-21: Add a note in security concerns about the presence of free-options in multi-party protocols

- core/cap-0021.md
This fixes a few typos in CAP-0021, fixes a comment that was out-of-sync between diff and text, and corrects an error about replay protection.
> CAP-0021: Minor fixes

- core/cap-0040.md
Add design rationale paragraph about how hint is derived for the signed payload signer.
@Shaptic pointed out that this isn't explained in the document, but there was specific intent to the hints design.
> CAP-40: Add rationale for how hint is derived

- core/cap-0044.md
Discussed with @jonjove earlier as part of CAP-45 refinement (https://github.com/stellar/stellar-protocol/pull/1152), the objective function we will be using is the squared l2 norm of the priced weighted demand, instead of the l2 norm.
> Change SpeedexSolutionComparisonHeuristic to squared l2 norm

- ecosystem/sep-0031.md
Clarifies when `sender_id` and `receiver_id` attributes are required for `POST /transactions` requests. 
Instead of referencing the body of `GET /info` responses, states that these parameters are be required if KYC is required.
> SEP31: clarify `sender_id` and `receiver_id` request attributes

- .github/workflows/mddiffcheck.yml
Note the tiny delta in whitespace relative to #1160:
```diff
-    - run: go install github.com/stellar/mddiffcheck @latest
+    - run: go install github.com/stellar/mddiffcheck@latest
```
This also aligns with `mddiffcheck`'s installation instructions, [here](https://github.com/stellar/mddiffcheck#usage).
> GHA fix: Install `mddiffcheck` outside of a module context

- ecosystem/sep-0031.md
The current description `The transaction should return to pending_receiver, though it is possible that the information could still need to be updated again.` implies all fields required by the transaction must be updated. 
It is less confusing to make that explicit.
> Update and clarify PATCH /transactions description

- core/cap-0021.md
- core/cap-0040.md
There are two CAP-0021 updates in this PR-
1. Duration is updated from int64 to uint64 because a negative `minSeqAge` doesn't make sense. We also removed all `ClaimPredicate` changes because they added additional implementation work with providing any functional benefits.
2.   Added a new error code `txBAD_MIN_SEQ_AGE_OR_GAP` in response to this PR comment - https://github.com/stellar/stellar-core/pull/3377#discussion_r830419321.
> CAP-0021 updates

- core/cap-0042.md
The updates include:
* Refined candidate value comparison to break total bid ties
* Example of `baseFee` role
* Clarification of the slight surge pricing algorithm change
> Updated CAP 42 with refined candiate value comparator and some clarification

- ecosystem/sep-0024.md
Closes #1184 
`completed_at` was defined as Optional fields in [SEP-6](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0006.md#transaction-history) and [SEP-31](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0031.md#get-transaction). However, the field is defined as Assigned null for in-progress transactions. in [SEP-24](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md#shared-fields-for-both-deposits-and-withdrawals).
Suggest to make the field consistent among all protocols.
> SEP-24: Change `completed_at` field to optional

- ecosystem/sep-0024.md
Since the `refunded` flag is being deprecated, MGI requested the `refunded` status.
> SEP-24: Added refunded transaction status

- ecosystem/sep-0009.md
> SEP-9: add `clabe_number`

- ecosystem/sep-0006.md
- ecosystem/sep-0031.md
Clarify that before sending the payment, the sending party should make a GET request to retrieve the expected `amount_in`.
Also added a few polishes to the text.
Some anchors could use additive fees in the transactions, which would make the amount proposed by the Wallet diverge from the one approved by the Anchor.
> SEP-6 + SEP-31: clarify that before sending the payment, the sending party should make a GET request to retrieve the expected `amount_in`

- core/cap-0046.md
A bunch of separate updates here:
- Added a big requirements section
- Removed most of the debated host objects -- can pick up in @jayz22's later work
- Switched {host, guest} environment and context as terms to match code, eliminated "guest environment" as a concept
- Renamed u63 to pos-u64 to match code, be less weird looking
- Updated implementation URLs to match current implementatione effort
- Mentioned rust implementation for host environment
- Added section on validity
- Added section on conversions
- Added section on comparison operation
- Expanded section on determinism, discussed WASM guarantees
- Expanded WASM rationale with reference to requirements
- Moved XDR forward ahead of host forms
- Added notes about relationship between tag numbers and XDR numbers
I _think_ this …
> CAP-0046: Delete objects, add requirements, conversions and validity, adjust language.

- core/cap-0047.md
This update has a few changes - 
1. Move mutability and ContractMetadata from the initial version to the Extensions section. 
2. Use a new `CreateContractTransaction` instead of the previously specified operations.
3. Use a Hash instead of int64 for the contractID.
4. Add host functions for creating and removing a contract.
> CAP-0047 updates

- ecosystem/sep-0031.md
resolves #1209 
Adds a `PUT /transactions/:id/callback` endpoint for Sending Anchor to request callback requests to a specified URL. This removes the need for Sending Anchors to poll the statuses of in-progress transactions, reducing the chatter between services, especially for anchors with high transaction throughput.
I considered adding this functionality into the existing `POST /transactions` and `PATCH /transactions` requests as an optional parameter, but figured that it was likely for Receiving Anchors who did not yet implement this feature to simply ignore the `callback_url` request attribute, leading Sending Anchors to believe their callback URL was accepted but never receiving the callback requests.
Note: originally we decided not to add this functionality in #636. I disagree with …
> SEP-31: add callback URL registration endpoint

- .github/workflows/mddiffcheck.yml
Update mddiffcheck to v1.1.0.
v1.1.0 includes automatic fetching of orphan commits, so we no longer need to manually specify a ref to fetch to get the orphaned commit. Manually specifying a ref was error prone because it assumed the commit would always be included in that ref's tree. Because refs, like PRs, on stellar-core are often force-pushed, there's a good chance commits get dropped from the ref's tree. This new version fixes that.
> Update mddiffcheck to v1.1.0

- core/cap-0051.md
> CAP-51: add several hostfns, add explaination of BigInt Convertion, SCStatus return.

- ecosystem/sep-0006.md
- ecosystem/sep-0024.md
- ecosystem/sep-0031.md
Adds the `expired` value to the transaction `status` attribute. For SEP-31 and SEP-6, which can use SEP-38 quotes, transactions should expire when quotes expire. In all other cases, the anchor is free to determine when transactions expire.
> Transfer SEPs: add the 'expired' status

- core/cap-0051.md
- Remove `call0..4` functions.
- Clean up `verify_sig_ed25519` fn signature and description.
> CAP-51 clean up

- core/cap-0042.md
Use a single component type with optional base fee instead of two components with non-optional fees.
> Unify `GeneralizedTxSet` component types in CAP-42.

- core/cap-0042.md
The `txSet` components have to be non-empty or otherwise it's possible to build tx sets that contain the same transactions
> CAP-42 - updated `txSet` validation rules.

- core/cap-0051.md
The max object handle is `UINT32_MAX`, which means the max number of host objects is `UINT32_MAX+1`
> CAP-0051:: fix max object count

- core/cap-0051.md
The current iteration has a circular dependency of hashes (hash of `TransactionResult` is stored in the meta, but `TransactionResult` stores a hash of all the hashes in the meta). This PR removes `TransactionResultExtensionV1` and instead stores the hash of the meta hashes in a new `TransactionResultPairV2`.
> Fix bug in CAP-0051 meta change

- ecosystem/sep-0012.md
Proposed changes for the callback status:
* Add **timestamp** field to ensure freshness of the call
* Add `X-Stellar-Signature` HTTP header: Base64 signature of the body. The signature is computed using the Anchor Stellar private key and verified using the corresponding public key
> SEP-12: Add callback signature

- core/cap-0051.md
Add a goal for trapping host fns to always provide a way to preemptively avoid the trap to developers.
It is important for flexibility, otherwise developers will not be able to write code that is allowed to fail. As an example why this is required, the `verify_sig_ed25519` fn traps and a developer has no way to avoid that trap if they need to check multiple signatures where not all verifications need to succeed. Related conversation: https://discord.com/channels/897514728459468821/993941320496316516.
cc @jonjove @sisuresh @graydon
> CAP-51: Add goal to provide ways around trapping host fns

- core/cap-0051.md
- Update their names and descriptions.
- Add a `binary_new_from_memcpy` which constructs a binary object and initializes its data in one op via `memcpy`. 
I will add more `memcpy` "helper" functions (as @graydon suggested) in follow-ups.
> CAP-51: update binary memcpy fns

- core/cap-0051.md
- core/cap-0056.md
Based on feedback from @paulbellamy, the indexes will be removed for now since Horizon would like to provide less filters for event streams and let the user just subscribe by contractID.
> CAP-0056 - remove indexes and fix ledger close meta

- ecosystem/sep-0012.md
It is unnecessary to use the Host HTTP header to verify the signature.
Using the expected host the callback should be sent to is enough to validate the signature.
> SEP-12: Do not use Host HTTP header

- ecosystem/sep-0006.md
- ecosystem/sep-0031.md
Add `quote_id` field to SEP-6 and SEP-31 transaction object schema.
When a quote was used to create the transaction, it's important to be able to figure that out by looking at the transaction response.
> SEP-6 & SEP-31: add `quote_id` field to the transaction object schema

- ecosystem/sep-0012.md
Make it explicit that the `account` and `memo` can be inferred from the JWT token.
Those fields were optional but it was not clear that the server should fill them in based on the JWT token.
> SEP-12: make it explicit that the `account` and `memo` can be inferred from the JWT token

- .gitignore
- ecosystem/sep-0024.md
Fixed small typo that left out `amount_out_asset` field description
> Fixed typo in SEP-24 doc

- contents/cap-0046/Stellar-contract.x
- core/cap-0046-02.md
- core/cap-0046.md
*Note*: This includes the configuration update commit that belongs to https://github.com/stellar/stellar-protocol/pull/1291, so the diff from CAP-46-09 commit should be ignored while reviewing this.
The main updates:
- Change `InvokeHostFunctionOp` to use XDR for contract creation args, as it's getting quite complex and doesn't ever need to be called from the contracts.
- Decouple WASM sources from the contract instances in order to deduplicate contracts that share their code.
- Change the contract-from-contract creation to use the code reference instead of the actual code
- Removed some outdated parts that don't allow well with the current implementation/vision
Some debatable decisions:
- This CAP still allows fusing WASM installation with contract instantiation. This could in theory be …
> [CAP-46-02] Updated contract lifecycle CAP.

- ecosystem/sep-0024.md
Fix the broken link of `needs customer information`. 
Changed "Pooled Account" to "Muxed Account".
> SEP-24 Fixed the missing link and changed pooled account to muxed account

- ecosystem/sep-0006.md
- ecosystem/sep-0024.md
This is a request from Lobstr. Currently, Polaris and other anchors return 400 when the specified language is not supported by the anchor. But because anchors don't provide a list of supported languages, the wallets have no choice but to attempt the request with the user's preferred language anyway. Therefore, anchors should be forgiving when an unsupported language is passed and default to english.
> SEP-24 & 6: update & add `lang` parameter to on relevant endpoints

- ecosystem/sep-0006.md
- ecosystem/sep-0024.md
- ecosystem/sep-0031.md
Receiving anchors often use custodial services to hold their on-chain assets, and these custodians often use omnibus accounts, so memos are used by the custodian to map inbound payments to their customer's balances.
To support this case, the standard allows Receiving anchors to provide a memo & memo type to use for each transaction in the `POST /transactions` request.
Sending anchors may also use custodial services to hold their on-chain assets, so in the event that a refund payment is necessary, sending anchors should be allowed to provide the receiving anchor a memo to use.
Thats why I'm adding two optional parameter to the `POST /transactions` request body, allowing the sending anchor to provide the receiving anchor with a memo to use when sending refund payments back.
> SEP-31, 24, & 6: add optional `refund_memo` to transaction initiation requests

- ecosystem/sep-0023.md
Add a contract strkey to SEP-23.
To use in applications that reference contracts deployed on Soroban, on the Stellar network.
- https://groups.google.com/g/stellar-dev/c/XWNpOIaXWBs
- https://discord.com/channels/897514728459468821/1048384084952502272
> SEP-23: Add a contract strkey

- ecosystem/sep-0024.md
Add updated_at field to the transaction object.
In the event of the anchor sends a callback with an older timestamp than the one that a wallet has proceeded, the callback can be safely discarded by the wallet.
> SEP-24: add updated_at field to transaction records

- ecosystem/sep-0006.md
- ecosystem/sep-0012.md
- ecosystem/sep-0024.md
- ecosystem/sep-0031.md
resolves #1328 
Updates the name of the signature header for callback requests from `X-Stellar-Signature` to `Signature`.
While this is technically a breaking change, the addition of the callback signature mechanism is new enough to not be concerned making existing implementations noncompliant.
> SEP 6,12,24,31: replace `X-Stellar-Signature` with `Signature`

- ecosystem/sep-0006.md
- ecosystem/sep-0012.md
- ecosystem/sep-0024.md
- ecosystem/sep-0031.md
A fast-follow PR for our discussion post-merge of #1333
> SEP-6,12,24,31: allow omission of X-Stellar-Signature

- ecosystem/sep-0006.md
- ecosystem/sep-0024.md
- ecosystem/sep-0031.md
Some SEPs were missing or had differing descriptions of the `refunded` status and `updated_at` transaction field. This PR makes their usage and definitions consistent across SEPs.
> SEP-6,24,31: unify use of `updated_at` and `refunded` status

- ecosystem/sep-0009.md
resolves #1332 
Adds `cvu_number` and `cbu_number` to SEP-9. We explored adding a generalized financial account field in #1334 and ultimately decided it added more complexity than it removed.
> SEP-9: add `cvu_number` and `cbu_number` fields

- ecosystem/sep-0009.md
After discussing with our partner, we realized that it is standard practice to use a single field that accepts both CVU & CBU numbers. We also want to add support for CVU & CVU aliases.
> SEP-9: remove `cvu_number`, add `cbu_alias`

- ecosystem/sep-0024.md
resolves #1342 
Makes the `account` parameter for the `POST /transactions/deposit/interactive` request optional to match the `POST /transactions/withdraw/interactive` request.
SEP-24 originally did not require SEP-10, and because of that, required that the client specify the destination account of the payment via the deposit request body. When we introduced SEP-10, we should have also updated the SEP to have anchors default to using the authenticated account as the destination.
This change will make the deposit request's `account` parameter definition consistent with the withdraw request's account parameter, which is also optional.
This is technically a breaking change for anchors that assume the `account` field will always be present, although in practice this is easy for wallets to work …
> SEP-24: make `account` deposit request parameter optional

- ecosystem/sep-0009.md
Adds `bank_account_type` to the list of SEP-9 fields, with initial supported values of `checking` or `savings`. Some jurisdictions have banking systems that require that the account type be specified in addition to the account number.
Note that `bank_account_type` does not indicate the format of `bank_account_number`, and should not be used to validate `bank_account_number`. 
If an anchor needs to be able to validate an account identifier, it should use other SEP-9 fields added specifically for the format they're looking to validate, such as `cbu_number` or `clabe_number`. These fields often contain pieces of information other than the user's account number with their bank. 
For example, CBU numbers contain identifiers for the bank, the bank branch, the type of account, and the account …
> SEP-9: add `bank_account_type`

- ecosystem/sep-0009.md
The primary use of SEP-9 fields has been for collecting information on users of Stellar-based applications, including both KYC data and off-chain financial account data.
However, SEP-9 was also intended to be used by organizations to provide information to their users. This is particularly relevant in the context of SEP-6, where organizations need to provide off-chain financial account information to their customers in order for customers to fund their deposit transactions.
This PR clarifies the set of fields that can be used by applications such as anchors to both request that information from customers and provide that information to customers.
Unrelatedly, it also makes formatting changes for improved readability.
> SEP-9: Defined shared financial account fields

- core/cap-0046-02.md
This is an initial pass of refreshing the lifecycle CAP.
> Refresh lifecycle CAP

- ecosystem/sep-0006.md
- ecosystem/sep-0024.md
Deprecate `/fee` endpoint for SEP-6.
Update SEP-24 changelog, as fee was already deprecated there, but not reflected in the changelog.
> SEP-6: Deprecate /fee endpont

- ecosystem/sep-0009.md
`bank_account_number` was missed when splitting personal KYC fields and financial account fields in #1367
> SEP-9: move bank_account_number into account-related fields section

- ecosystem/sep-0009.md
SEP-6 will provide structured off-chain deposit instructions which can include deposits to an organization's crypto accounts. This adds the `crypto_address` and `crypto_memo` fields to the standard.
> SEP-9: Add crypto fields to financial account fields

- ecosystem/sep-0031.md
This PR deprecates and makes optional the `fields` object in the `GET /info` response, the `POST /transactions` requests, and the `PATCH /transactions/:id` requests. It also deprecates the use of the `pending_transaction_info_updates` status, since this was only used to request per-transaction fields.
To our knowledge this object is not used, and was originally added to account for the possibility of non-standard per-transaction fields. However, supporting the use of non-standard fields in our tools & services meant to make implementing SEP-31 easier is difficult, and given the lack of usage in the ecosystem, it makes sense to deprecate the object and encourage the use of standard SEP-9 fields.
> SEP-31: deprecate per-transaction fields

- contents/cap-0046/Stellar-contract-config-setting.x
- contents/cap-0046/Stellar-contract-meta.x
- contents/cap-0046/Stellar-contract-spec.x
- contents/cap-0046/Stellar-contract.x
- core/cap-0046-05.md
Two separate things here:
- Update the XDR in contents/cap-0046 -- I don't think we've updated it in a while
- Actually update the text of CAP-0046-05 to reflect instance storage, expiry, and therefore "storage types"
> update CAP 0046-05 smart contract data

- ecosystem/README.md
The link was pointing (I assume) to a draft filename. Now, it points correctly to the `sep-0040.md` file
> SEP-0040 Correct the SEP link in `ecosystem/README.md` file

- ecosystem/sep-0041.md
Remove the `spendable_balance` contract function from the contract interface captured in SEP-41.
The difference between balance and spendable balance is subtle. It is clear what each should return for most tokens. But it is not clear on which should be used by tokens wishing to read the balance.
In some use cases spendable balance is clearly beneficial to use if the intent is to transfer or do something with all available balance.
In other use cases on the surface it doesn't matter which one would be used, but the downstream ramifications aren't clear. For example, if my contract reads the balance for a specific use case, and someone else using my contract then decides to transfer that amount as a result, I may make the assumption balance is the best to use while the caller of my contract …
> SEP-41: Remove spendable_balance

- core/cap-0046-07.md
Update CAP-46-07 with the refundable->resource fee semantics changes.
Also did a passing-by update for ledger-wide IO limits.
> Update CAP-46-07 with the refundable->resource fee semantics changes.

- core/cap-0046-03.md
Update host function interface with changes in the `env` for the past ~2 months.
> Update host function interface to the latest `env`

- ecosystem/sep-0006.md
This makes the `account_id` field in the `withdraw` and `withdraw-exchange` response optional. This is to support Anchors integrating with a Custodian, in which a Stellar address other than the asset's distribution account is used as the `withdraw_anchor_account`. This is to prevent users from accidentally depositing to the wrong address in case the `withdraw_anchor_account` is changed during the SEP transaction's lifecycle.
> SEP-6: Make `account_id` optional in withdraw response

- ecosystem/sep-0009.md
Sometimes user is referred to the application from an external source, and Application may want to know the external source's ID, thus the suggested new field in SEP-9
> [SEP-9] Add referral_id

- ecosystem/sep-0006.md
Since SEP-6 does not use SEP-12 types, having the `required_customer_info_updates` be included in the SEP-12 GET /customer response would block new transactions due to unrelated KYC requirements from a previous SEP-6 deposit/withdrawal.
> SEP-6: Get required KYC fields from transaction object only

- core/README.md
- core/cap-0046-01.md
- core/cap-0046-02.md
- core/cap-0046-03.md
- core/cap-0046-05.md
- core/cap-0046-06.md
- core/cap-0046-07.md
- core/cap-0046-08.md
- core/cap-0046-09.md
- core/cap-0046-10.md
- core/cap-0046-11.md
- core/cap-0046-12.md
- core/cap-0046.md
Marking 12 Soroban CAPs `FCP: Accepted`
> Rice2000 soroban caps fcp

- core/README.md
- core/cap-0046-01.md
- core/cap-0046-02.md
- core/cap-0046-03.md
- core/cap-0046-05.md
- core/cap-0046-06.md
- core/cap-0046-07.md
- core/cap-0046-08.md
- core/cap-0046-09.md
- core/cap-0046-10.md
- core/cap-0046-11.md
- core/cap-0046-12.md
- core/cap-0046.md
Final Comment Period is now complete, and there were no questions or objections raised, so this PR changes the designation of the Soroban CAPs from `FCP: Acceptance` to `Accepted`
> Mark Soroban CAPs as Accepted

- core/cap-0051.md
Add client data JSON example to CAP-51.
It's helpful to readers visually be able to see what a full client data JSON looks like.
> CAP-51: Add client data JSON example

- ecosystem/sep-0012.md
Currently, to verify any field it's required to call `PUT /customer/verification` by suffixing said field with `_verification`. This proposal deprecated this approach in favor of more simplified flow  
Merge functionality of `PUT /customer//verification` with `PUT /customer`. Now, client should first fields via `PUT /customer`, and then verify them (if needed) in the same manner as before (suffix field with `_verification` and pass verification information as value of the field)
> Deprecate `PUT /verifcation` and update verification process for SEP-12

- ecosystem/sep-0031.md
Mirroring changes of #1429 for SEP-31 protocol
> ANCHOR-505: Add fee details field to SEP-31 transaction object

- core/README.md
- core/cap-0053.md
- core/cap-TBD.md
Add CAP to extend the TTL for contract code and instance separately. This is an ecosystem proposal, https://github.com/stellar/stellar-protocol/discussions/1447
> Add CAP to extend the TTL for contract code and instance separately

- core/cap-0054.md
- core/cap-0056.md
Just a couple additions that came up in protocol meeting today around upgrading cost models and clarifying that the cache cost-charging behaviour is somewhat logically distinct from the _actual existence_ of a cache.
> Address some review comments from protocol meeting

- ecosystem/sep-0009.md
> SEP-9 : Add `external_transfer_memo` field to Financial Account Fields

- ecosystem/sep-0009.md
Depending on the integration (e.g the [Stellar Disbursement Platform](https://github.com/stellar/stellar-disbursement-platform-backend/pull/256)) parts may want to hash the mobile number to increase security during the data sharing between wallets and Anchors.
> SEP-9 : Add `mobile_number_format` field to Natural Person Fields

- core/README.md
- core/cap-0057.md
See https://github.com/stellar/stellar-protocol/discussions/1480 for discussion.
> cap-57 initial draft: State Archival Persistent Entry Eviction

- core/cap-0058.md
The CAP specifies the necessary protocol changes for supporting contract constructors in Soroban. The CAP is motivated by the following discussion: https://github.com/stellar/stellar-protocol/discussions/1501
> Add CAP-58 - support for contract constructors.

- ecosystem/sep-0006.md
- ecosystem/sep-0008.md
- ecosystem/sep-0012.md
- ecosystem/sep-0030.md
- ecosystem/sep-0031.md
**SEP-6, 8, 30** 
Nits and prettify
**SEP-12** 
Nits
**SEP-31**
1. KYC completion is no longer required before creating a SEP-31 transaction. Sending anchor can optionally pre-register customers and use the obtained `sender_id` or `receiver_id` to create transaction, or leave these fields empty. 
2. After the transaction is created, the Sending anchor will call `GET /customer?transaction_id=<sep31-txn-id>&type=` to determine the required fields for each type of client, and then make a `PUT` call to the same endpoint to update the information
> [ANCHOR-719] Update SEP31 to replace SEP12 with async kyc flow

- core/cap-0023.md
The existing lines 227–230 do not clearly define the logic for claimable balance IDs, per #1512. However, thanks to [clarification](https://github.com/stellar/stellar-docs/issues/836#issuecomment-2264080490) from @Shaptic, this update clarifies the innovative calculations deployed. Lastly, the revisions polish what was otherwise an excessive run-on dependent clause of mathematical relations from lines 334–337.
> 📌 Specify exact ClaimableBalanceID.v0 arithmetic

- .github/workflows/prettier.yml
- package.json
We saw some failures with original job in https://github.com/stellar/stellar-protocol/pull/1515#event-13782930566
Which shouldn't fail (and doesn't fail locally), I think it's something with `prettier-action` so replaced it with more straightforward approach of just calling yarn script
> Update prettier job

- core/cap-0046-06.md
The implementation emits this event. This PR just brings the CAP up to date.
> Add asset name to SAC events

- core/cap-0058.md
- Update for supporting v1 'create contract' auth payload 
- Clarify the semantics of CREATE_CONTRACT_HOST_FN w.r.t constructor support.
> Small updates of CAP-58

- core/cap-0061.md
- ecosystem/sep-0044.md
Move memo into fifth event topic field in SEP-44 and CAP-61.
The fourth event topic already being used in the built-in token implementation is problematic as it causes existing applications already ingesting transfer events to need to change which topic field they expect the sep11 asset name to be in.
Moving the memo to the fifth topic field is a small change that increases the chance SEP-44 is a forward compatible change.
> SEP-44, CAP-61: Move memo into fifth event topic

- ecosystem/sep-0044.md
Minor edits to undefine the fourth event topic to SEP-44.
SEP-44 currently partially defines the fourth event topic field, where-as it is better if the proposal plays as little role as possible in defining what that field contains. Implementations should largely ignore the field rather than expect any specific behavior around it to allow for other SEPs that define usage of it.
Dependent on the following changes merging first:
- https://github.com/stellar/stellar-protocol/pull/1545
> SEP-44: Minor edits to undefine the fourth event topic

- core/README.md
- core/cap-0051.md
- core/cap-0053.md
- core/cap-0054.md
- core/cap-0055.md
- core/cap-0056.md
- core/cap-0058.md
- core/cap-0059.md
- core/cap-0060.md
Updated state of the following CAPs to "FCP: Accepted" following the unanimous approval from the CAP Core Team over email to the stellar developer mailing list.
1. [CAP-0058](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0058.md): Addition of a constructor to Soroban's flavor of Rust.
2. [CAP-0059](https://github.com/stellar/stellar-protocol/blob/9995d73a0d9739ead56f57334fab499eaf55fc0f/core/cap-0059.md): Addition of BLS12-381 curve and required field arithmetics.
3. [CAP-0060](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0060.md): Increase performance by upgrading Soroban's VM.
> Update CAPs state to FCP: Accepted

- core/README.md
In re [D799](https://github.com/stellar/stellar-docs/issues/799), stars for bullet points make my insides repulse, especially when the label thereater is bold with stars.[^existing]
[^existing]: _See also_ parallel code at [C118&ndash;123](https://github.com/stellar/stellar-protocol/blob/eb401f932258c827a5b4a2e14aea939affcd2b02/core/README.md?plain=1#L118-L123) and [all SEP info](https://github.com/stellar/stellar-protocol/blob/eb401f932258c827a5b4a2e14aea939affcd2b02/ecosystem/README.md?plain=1#L5-L219) employing hyphens.
> Change bullet * to - for readability due to adjacent **

- core/README.md
- core/cap-0058.md
- core/cap-0059.md
- core/cap-0060.md
Updating CAP statuses for Protocol 22:
58 and 59 --> Implemented
60 back to Draft
> Rice2000 protocol 22 cap status

- core/cap-0046-06.md
Change the events emitted by Stellar Asset Contracts to match the implementation.
If you look at the code of what events are emitted, they don't currently match the specification, with data values incorrect, as well as parameters.
https://github.com/stellar/rs-soroban-env/blob/v21.2.2/soroban-env-host/src/builtin_contracts/stellar_asset_contract/event.rs#L56-L71
When reviewing, please thoroughly check the changes with the code. This is the second time we're correcting the events in the CAP with the implementation, having already attempted to get it aligned at least one other time since implementation, and these docs should be reliable, so it's worth two people thoroughly confirming.
cc @stellar/contract-committers
> CAP-0046-06: Fix events emitted

- core/cap-0057.md
This update makes minor updates to evicted entry meta, provides an optimization preventing some writes of DELETED keys to the AST, and distinguishes between proof requirements when creating an entry for the first time vs. recreating an entry that was previously deleted.
The optimization for deleted keys checks the archive before writing a deleted key, and only writes the key if an ARCHIVED entry with the same key exists in the AST. If no ARCHIVED entry exists, we don't need to write the deleted key, as there in no double restore attack to prevent. This can be done safely and efficiently via the archival filters.
Unfortunately, I've recently realized an issue in new entry creation proofs wrt recreated entries. If a key has never existed before, we can optimize proofs-of-nonexistence via …
> Added proof requirements to entry recreation

- core/README.md
- core/cap-0065.md
This describes some recent work (targeting protocol 23) that builds on the work of CAPs 62 and 63 to unlock a reusable (cross-ledger) module cache for soroban.
> Initial CAP-0065 - Reusable module cache

- core/README.md
- core/cap-0066.md
This is the initial draft CAP for in-memory Soroban state and automatic entry restoration via `InvokeHostFunctionOp`. It depends on partial state archival from CAP-0062, but not full state archival of CAP-0057.
> Initial draft cap 63

- core/cap-0063.md
- core/cap-0064.md
- core/cap-0066.md
- core/cap-0067.md
We should rename `SorobanTransactionMeta`, but that can be done in a follow up change to this CAP.
> CAP-0067 Update

- core/cap-0067.md
This allows events to be emitted at the operation level.
> CAP-0067 - Emit events at the operation layer

- ecosystem/sep-0045.md
This adds the initial draft for SEP-0045, which is a proposal for a new API to allow for web authentication for contract accounts. It is based on SEP-10 which is the web authentication API for classic accounts but with modifications to support Soroban's authentication model.
This is based on a [previous PR](https://github.com/stellar/stellar-protocol/pulls?q=is%3Apr+is%3Aclosed+soroban+auth+) authored by @leighmcculloch.
> SEP-45: Stellar Web Authentication for Contract Accounts

- core/cap-0065.md
The CAP should reference CAP-0066 (Soroban In-memory Read Resource), not CAP-0063 (Parallelism-friendly Transaction Scheduling).
> Fix CAP-0065 link to reference CAP-0066

- core/README.md
- core/cap-0068.md
This is a 'catch-all' CAP for closing some gaps in the host interface. These are meant to be very simple, so I don't see much value in creating multiple CAPs, even though the functions are not always related to each other.
> Add CAP-68 - new host functions for protocol 23.

- core/cap-0064.md
This is just a cosmetic change for more logical field grouping (payload, then signature for credentials; network, then credentials, then execution-related fields for the signature payload preimage).
> Reorder fields in CAP-64 XDR changes.

- core/cap-0063.md
Unfortunately, cumulative updates would require some significant meta structure changes. That's why I'm using the max aggregation instead. I've also added a section on the updated meta semantics (unfortunately there is no way to make the meta processing completely trivial for TTL).
> Update TTL reconciliation logic in CAP-63.

- core/cap-0066.md
Updates CAP 66 as follows:
- Removes "evicted" state from protocol, all archived entries are considered disk reads
- Clarifies meta changes for entries that are restored and modified in the same transaction
- adds detail on changes required for `restorePreamble` for TXs that restore too many entries for auto restore to work
- Discuses DOS attacks and mitigations wrt in memory read limits
> Removed evicted state from cap 66

- core/cap-0062.md
Changes `sorobanLiveStateTargetSizeBytes` from tracking on-disk Soroban state to tracking in-memory live Soroban state.
> sorobanLiveStateTargetSizeBytes now measures in-memory live soroban state

- core/cap-0062.md
- core/cap-0066.md
This updates gives write fees a constant per kb rate. Rent fees have been changed to depend on the current amount of live, in-memory soroban state. Rent is charged based on the in-memory size of the given entry, not the on-disk size. For `CONTRACT_DATA` this is irrelevant, since on-disk and in-memory size is the same. For `CONTRACT_CODE`, the instantiated module size is used, as reported by the cost model.
> Updated to dynamic rent fee + constant write fee

- core/cap-0067.md
- [functional] State that muxed source accounts are unconditionally prohibited for Soroban. The currently specified rule is in fact incorrect, and in general leaving the muxed source account support for Soroban seems like a footgun.
- [non-functional] Move the fields in ScAddress XDR around a bit to group the 'soroban-representable' types together
- [non-functional] Extend multiplexing section a bit for some context/more detailed definitions.
- [non-functional] Simplify/clarify the rules for emitting the events with muxed sources/destinations, also close some gaps (like it wasn't clearly specified that CB/LP addresses won't ever have memo attached)
- [non-functional] Clarify that fee events are emitted at tx level (and not operation level)
> Minor updates/clarifications for CAP-67

- ecosystem/sep-0023.md
Add two new strkey types for liquidity pool and claimable balance, including examples of valid and invalid addresses.
In support of the upcoming changes to SEP-23 for CAP-67.
- https://github.com/stellar/rs-stellar-strkey/pull/74
> SEP-23: Add Liquidity Pool and Claimable Balance Strkeys

- core/cap-0067.md
We currently clear all `OperationMeta` when a transaction fails, @jayz22 mentioned that with the way the xdr is setup in the CAP, we wouldn't be able to do that if the diagnostics vector inside `OperationMetaV2` is used. We then realized that we don't gain much from having diagnostics in `OperationMetaV2` instead of just using the vector in `TransactionMetaV4`. Classic operations won't emit any diagnostics in v23, and if we want them to in the future, we can just modify the diagnostic events to contain the operation id.
> CAP-0067 - Remove op level diagnostic event vector

- ecosystem/README.md
- ecosystem/sep-0047.md
Add a new SEP-0047 that defines how contracts indicate which SEPs they implement using meta entries.
Contracts currently have no standardized way to declare which SEP interfaces they implement. See proposal. This proposal has been discussed here:
- https://github.com/stellar/stellar-protocol/discussions/1659
> Add Standard Interface Discovery SEP

- core/README.md
- core/cap-0046-06.md
- core/cap-0062.md
- core/cap-0063.md
- core/cap-0064.md
- core/cap-0065.md
- core/cap-0066.md
- core/cap-0067.md
- core/cap-0068.md
- core/cap-0069.md
Flip `Protocol Version` of draft CAPs to TBD and move the statuses to Awaiting Decision. 
Once CAP is accepted and implemented we would set the Protocol Version that they would be available in.
> Fix the status on CAPs 62-69 and the protocol version

- ecosystem/README.md
Add SEP-0048 Contract Interface Specification to the ecosystem README table.
The new SEP-0048 draft proposal needs to be listed with other SEPs for discoverability.
> SEP-48: Add Contract Interface Specification to table

- ecosystem/sep-0045.md
- Rename `Home Domain Address` to `Server Account`
- Rename `Client Domain Address` to `Client Domain Account`
- Rename `home_domain_address` argument to `web_auth_domain_account`
- Rename `client_domain_address` argument to `client_domain_account`
- Add `home_domain` argument to `web_auth_verify` function
- Mark nonce verification as required and add a replay prevention section
- Clarify client domain signing sentence
> SEP-45: Replay prevention + argument name fixes

- ecosystem/sep-0010.md
In Step 9 of the verification flow, the signature count can be three if the transaction has a Manage Data operation with key client_domain. 
This is a bug.
> [ANCHOR-1031] Fix signature count when a manage data operation with  is present.

- .github/workflows/mddiffcheck.yml
Update the GitHub Action workflow for mddiffcheck to use v1.2.0 which has built-in support for multiple repos.
Mdiffcheck v1.2.0 has built in support for multiple repos, only checking repos out once. The workflow was updated temporarily to run once for every doc, instead of once for the whole repo, but running once for every doc means checking out the stellar-core repo 70+ times.
> Update mddiffcheck workflow for multiple repos

- .github/workflows/mddiffcheck.yml
Update the mddiffcheck workflow to use v1 instead of pinning to specific patch v1.2.0.
Using a major version allows automatic updates to minor and patch versions, reducing maintenance while ensuring compatibility.
I wanted to update to v1.2.1, but we really don't need to pin versions for this tool.
> Loosen mddiffcheck version to v1 instead of v1.2.0

- core/cap-0070.md
As discussed in the protocol meeting, this change tightens implementation defined SCP timing limits. It also adds a section discussing the reasoning behind these tighter bounds and explains that while the limits are implementation defined (i.e. not written as a network config entry), they should only be changed on protocol boundaries.
> Tighter limits on CAP 70 values

- ecosystem/README.md
Update the links in the ecosystem README to include the GitHub discussion forum and Stellar Dev Discord as channels for discussing SEPs.
These channels are now active communities for Stellar development discussions but were missing from the documentation. These communities are the primary place that discussion appears to be happening now-days.
> Update forum links for SEP discussions

- ecosystem/README.md
Remove SEP Team Members list.
The review, approval, and merge workflow process needs some work as @orbitlens highlights in #1728, but irrespective of that this list doesn't seem to serve a purpose as it's consistently out of date, as evidence by it containing the names of folks who are not actively engaged in discussions on new SEPs.
Unlike CAPs, that have a formal list of folks who review and approve the acceptance of CAPs, SEPs don't have a formal list of accepters and have a "lightweight process for approval," as noted by the ecosystem README. SEPs can be proposed and merged on a loose set of requirements as noted in the README.
cc @rice2000 @tomerweller @JakeUrban @accordeiro @marcelosalloum @orbitlens
> Remove SEP Team Members List

- core/cap-0066.md
In-memory read limit was just a proxy for what we really want: a limit on the maximum overall footprint length. With this change this limit is named and specified explicitly.
> CAP-66: Minor update semantics for `txMaxInMemoryReadEntries`.

- core/README.md
- core/cap-0062.md
- core/cap-0063.md
- core/cap-0065.md
- core/cap-0066.md
- core/cap-0067.md
- core/cap-0068.md
- core/cap-0069.md
- core/cap-0070.md
Now that we have Core CAP Team's approval in stellar-dev mailing list, updating the CAPs for Protocol 23 to `FCP: Accepted status`.
> Update Protocol 23 CAPs to FCP: Accepted status

- .github/workflows/mddiffcheck.yml
- ecosystem/sep-0051.md
Change 64-bit signed and unsigned integers (Hyper) as well as the `ScVal` 128/256-bit types to use JSON string representations instead of JSON number or JSON maps.
JavaScript cannot precisely represent numbers larger than 53 bits due to IEEE 754 limitations. String representation ensures compatibility with native JavaScript JSON parsers.
See https://github.com/stellar/stellar-protocol/discussions/1702#discussioncomment-12964633 for more discussion.
> SEP-51: Encode 64bit int (Hyper) and 128/256bit types as strings

- core/cap-0066.md
Previously it was assumed that Wasm entries are only stored in the module cache, i.e. the actual XDR doesn't leave a memory footprint. However, this would have been hard to implement in practice, which is why code entries will also be stored in the Soroban entry cache. Since the minimum size increase for Wasm is 3x now, updated the rent discount from 2x to 3x and adjusted the fees accordingly, such that the overall rent cost decrease for Wasm stays at 20x.
> CAP-66: Specify that Wasm entries are also cached in memory.

- ecosystem/README.md
- ecosystem/sep-0054.md
- ecosystem/sep-datastore.md
Adds a SEP to document how galexie stores ledger metadata. By formally specifying the data format we can enable third-party developers to build compatible data stores and clients for retrieving ledger metadata.
See also https://github.com/stellar/go/issues/5577 for motivation
> Add SEP for ledger metadata storage

- ecosystem/sep-0054.md
In response to feedback from @leighmcculloch in https://github.com/orgs/stellar/discussions/1678#discussioncomment-13812481 and https://github.com/orgs/stellar/discussions/1678#discussioncomment-13812511 , I have decided to update the sep with the following changes:
- only `/<ledgers-path>` is configurable and the config file will located at `/<ledgers-path>/.config.json`. The advantage of this approach is that the config file is always co-located with the partitions. Also, because the config filename starts with a period, it will always precede the partitions lexicographically, whereas a filename of "config.json" could be interspersed lexicographically with the partition folders. Having a fixed config file path is easier for the operator because they only need to configure …
> Update SEP 0054 to use fixed config file path

- ecosystem/README.md
Change the title of SEP-47 in the ecosystem README to Contract Interface Discovery, to match the title of the SEP.
In https://github.com/stellar/stellar-protocol/pull/1703 I renamed SEP-47 to Contract Interface Discovery and updated the ecosystem README. In https://github.com/stellar/stellar-protocol/pull/1704 I accidentally renamed it back, probably as the result of a botched merge fix up.
> SEP-47: Fix title in ecosystem README

- core/README.md
- core/cap-0071.md
This CAP improves the developer experience for delegating the authentication logic from one account contract to another. A new use case for the authentication delegation is introduced in the upcoming CAP-72, that adds the authentication delegation capabilities to G-accounts.
> Add CAP-71 - Authentication delegation for custom accounts

- core/cap-0071.md
This is not strictly required, but not doing this would introduce some unnecessary annoyance for the contract implementation and transaction building, including CAP-72 as well.
> CAP-71 - Add delegated signers getter.

- core/cap-0072.md
After describing the contract data-based approach in the first iteration, it became pretty apparent that this approach is more complex than I've originally anticipated, and just extending the `Signer` seems like a much easier way to go (as proven by the -100 lines of diffs in this PR). Also, if we want to do trustline management from Soroban, we'd need to do pretty much the same thing anyways.
> CAP-72 - Switch to the approach of modifying the AccountEntry directly
